
package com.globalsight.www.webservices;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-03-23T11:44:21.206+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class WebService4AEM_WebService4AEMPort_Server{

    protected WebService4AEM_WebService4AEMPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new WebService4AEMPortImpl();
        String address = "http://10.10.215.103:8080/globalsight/aemServices/WebService4AEM";
        Endpoint.publish(address, implementor);
    }
    
//    public static void main(String args[]) throws java.lang.Exception { 
//        new WebService4AEM_WebService4AEMPort_Server();
//        System.out.println("Server ready..."); 
//        
//        Thread.sleep(5 * 60 * 1000); 
//        System.out.println("Server exiting");
//        System.exit(0);
//    }
}
