
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.globalsight.www.webservices;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-03-23T11:44:21.187+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "WebService4AEM",
                      portName = "WebService4AEMPort",
                      targetNamespace = "http://webservices.globalsight.com/",
                      wsdlLocation = "http://10.10.215.103:8080/globalsight/aemServices/WebService4AEM?wsdl",
                      endpointInterface = "com.globalsight.www.webservices.WebService4AEM")
                      
public class WebService4AEMPortImpl implements WebService4AEM {

    private static final Logger LOG = Logger.getLogger(WebService4AEMPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getFileProfileInfoEx(java.lang.String  arg0 )*
     */
    public java.lang.String getFileProfileInfoEx(java.lang.String arg0) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getFileProfileInfoEx");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getImportExportStatus(java.lang.String  arg0 )*
     */
    public java.lang.String getImportExportStatus(java.lang.String arg0) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getImportExportStatus");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getJobExportWorkflowFiles(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 )*
     */
    public java.lang.String getJobExportWorkflowFiles(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getJobExportWorkflowFiles");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#login(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String login(java.lang.String arg0,java.lang.String arg1) throws WebServiceException_Exception    { 
        LOG.info("Executing operation login");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#addJobComment(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)byte[]  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 )*
     */
    public java.lang.String addJobComment(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,byte[] arg4,java.lang.String arg5,java.lang.String arg6) throws WebServiceException_Exception    { 
        LOG.info("Executing operation addJobComment");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getJobStatus(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getJobStatus(java.lang.String arg0,java.lang.String arg1) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getJobStatus");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#uploadFileForInitial(com.globalsight.www.webservices.WrapHashMap  arg0 )*
     */
    public java.lang.String uploadFileForInitial(com.globalsight.www.webservices.WrapHashMap arg0) throws WebServiceException_Exception    { 
        LOG.info("Executing operation uploadFileForInitial");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getDownloadableJobs(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getDownloadableJobs(java.lang.String arg0,java.lang.String arg1) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getDownloadableJobs");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#createJob(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 )*
     */
    public void createJob(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,java.lang.String arg4,java.lang.String arg5) throws WebServiceException_Exception    { 
        LOG.info("Executing operation createJob");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#uploadFile(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)byte[]  arg4 )*
     */
    public void uploadFile(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,byte[] arg4) throws WebServiceException_Exception    { 
        LOG.info("Executing operation uploadFile");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getJobExportFiles(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getJobExportFiles(java.lang.String arg0,java.lang.String arg1) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getJobExportFiles");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

    /* (non-Javadoc)
     * @see com.globalsight.www.webservices.WebService4AEM#getUniqueJobName(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public java.lang.String getUniqueJobName(java.lang.String arg0,java.lang.String arg1) throws WebServiceException_Exception    { 
        LOG.info("Executing operation getUniqueJobName");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WebServiceException_Exception("WebServiceException...");
    }

}
