
package com.globalsight.www.webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-03-23T11:44:21.183+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "WebServiceException", targetNamespace = "http://webservices.globalsight.com/")
public class WebServiceException_Exception extends Exception {
    
    private com.globalsight.www.webservices.WebServiceException webServiceException;

    public WebServiceException_Exception() {
        super();
    }
    
    public WebServiceException_Exception(String message) {
        super(message);
    }
    
    public WebServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WebServiceException_Exception(String message, com.globalsight.www.webservices.WebServiceException webServiceException) {
        super(message);
        this.webServiceException = webServiceException;
    }

    public WebServiceException_Exception(String message, com.globalsight.www.webservices.WebServiceException webServiceException, Throwable cause) {
        super(message, cause);
        this.webServiceException = webServiceException;
    }

    public com.globalsight.www.webservices.WebServiceException getFaultInfo() {
        return this.webServiceException;
    }
}
