
package com.globalsight.www.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-03-23T11:44:21.162+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class WebService4AEM_WebService4AEMPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.globalsight.com/", "WebService4AEM");

    private WebService4AEM_WebService4AEMPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebService4AEM_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebService4AEM_Service ss = new WebService4AEM_Service(wsdlURL, SERVICE_NAME);
        WebService4AEM port = ss.getWebService4AEMPort();  
        
        {
        System.out.println("Invoking getFileProfileInfoEx...");
        java.lang.String _getFileProfileInfoEx_arg0 = "";
        try {
            java.lang.String _getFileProfileInfoEx__return = port.getFileProfileInfoEx(_getFileProfileInfoEx_arg0);
            System.out.println("getFileProfileInfoEx.result=" + _getFileProfileInfoEx__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getImportExportStatus...");
        java.lang.String _getImportExportStatus_arg0 = "";
        try {
            java.lang.String _getImportExportStatus__return = port.getImportExportStatus(_getImportExportStatus_arg0);
            System.out.println("getImportExportStatus.result=" + _getImportExportStatus__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getJobExportWorkflowFiles...");
        java.lang.String _getJobExportWorkflowFiles_arg0 = "";
        java.lang.String _getJobExportWorkflowFiles_arg1 = "";
        java.lang.String _getJobExportWorkflowFiles_arg2 = "";
        try {
            java.lang.String _getJobExportWorkflowFiles__return = port.getJobExportWorkflowFiles(_getJobExportWorkflowFiles_arg0, _getJobExportWorkflowFiles_arg1, _getJobExportWorkflowFiles_arg2);
            System.out.println("getJobExportWorkflowFiles.result=" + _getJobExportWorkflowFiles__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_arg0 = "";
        java.lang.String _login_arg1 = "";
        try {
            java.lang.String _login__return = port.login(_login_arg0, _login_arg1);
            System.out.println("login.result=" + _login__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addJobComment...");
        java.lang.String _addJobComment_arg0 = "";
        java.lang.String _addJobComment_arg1 = "";
        java.lang.String _addJobComment_arg2 = "";
        java.lang.String _addJobComment_arg3 = "";
        byte[] _addJobComment_arg4 = new byte[0];
        java.lang.String _addJobComment_arg5 = "";
        java.lang.String _addJobComment_arg6 = "";
        try {
            java.lang.String _addJobComment__return = port.addJobComment(_addJobComment_arg0, _addJobComment_arg1, _addJobComment_arg2, _addJobComment_arg3, _addJobComment_arg4, _addJobComment_arg5, _addJobComment_arg6);
            System.out.println("addJobComment.result=" + _addJobComment__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getJobStatus...");
        java.lang.String _getJobStatus_arg0 = "";
        java.lang.String _getJobStatus_arg1 = "";
        try {
            java.lang.String _getJobStatus__return = port.getJobStatus(_getJobStatus_arg0, _getJobStatus_arg1);
            System.out.println("getJobStatus.result=" + _getJobStatus__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadFileForInitial...");
        com.globalsight.www.webservices.WrapHashMap _uploadFileForInitial_arg0 = null;
        try {
            java.lang.String _uploadFileForInitial__return = port.uploadFileForInitial(_uploadFileForInitial_arg0);
            System.out.println("uploadFileForInitial.result=" + _uploadFileForInitial__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDownloadableJobs...");
        java.lang.String _getDownloadableJobs_arg0 = "";
        java.lang.String _getDownloadableJobs_arg1 = "";
        try {
            java.lang.String _getDownloadableJobs__return = port.getDownloadableJobs(_getDownloadableJobs_arg0, _getDownloadableJobs_arg1);
            System.out.println("getDownloadableJobs.result=" + _getDownloadableJobs__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createJob...");
        java.lang.String _createJob_arg0 = "";
        java.lang.String _createJob_arg1 = "";
        java.lang.String _createJob_arg2 = "";
        java.lang.String _createJob_arg3 = "";
        java.lang.String _createJob_arg4 = "";
        java.lang.String _createJob_arg5 = "";
        try {
            port.createJob(_createJob_arg0, _createJob_arg1, _createJob_arg2, _createJob_arg3, _createJob_arg4, _createJob_arg5);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking uploadFile...");
        java.lang.String _uploadFile_arg0 = "";
        java.lang.String _uploadFile_arg1 = "";
        java.lang.String _uploadFile_arg2 = "";
        java.lang.String _uploadFile_arg3 = "";
        byte[] _uploadFile_arg4 = new byte[0];
        try {
            port.uploadFile(_uploadFile_arg0, _uploadFile_arg1, _uploadFile_arg2, _uploadFile_arg3, _uploadFile_arg4);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getJobExportFiles...");
        java.lang.String _getJobExportFiles_arg0 = "";
        java.lang.String _getJobExportFiles_arg1 = "";
        try {
            java.lang.String _getJobExportFiles__return = port.getJobExportFiles(_getJobExportFiles_arg0, _getJobExportFiles_arg1);
            System.out.println("getJobExportFiles.result=" + _getJobExportFiles__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUniqueJobName...");
        java.lang.String _getUniqueJobName_arg0 = "";
        java.lang.String _getUniqueJobName_arg1 = "";
        try {
            java.lang.String _getUniqueJobName__return = port.getUniqueJobName(_getUniqueJobName_arg0, _getUniqueJobName_arg1);
            System.out.println("getUniqueJobName.result=" + _getUniqueJobName__return);

        } catch (WebServiceException_Exception e) { 
            System.out.println("Expected exception: WebServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
