package com.globalsight.www.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-03-23T11:44:21.200+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://webservices.globalsight.com/", name = "WebService4AEM")
@XmlSeeAlso({ObjectFactory.class})
public interface WebService4AEM {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFileProfileInfoEx", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetFileProfileInfoEx")
    @WebMethod
    @ResponseWrapper(localName = "getFileProfileInfoExResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetFileProfileInfoExResponse")
    public java.lang.String getFileProfileInfoEx(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getImportExportStatus", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetImportExportStatus")
    @WebMethod
    @ResponseWrapper(localName = "getImportExportStatusResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetImportExportStatusResponse")
    public java.lang.String getImportExportStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJobExportWorkflowFiles", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetJobExportWorkflowFiles")
    @WebMethod
    @ResponseWrapper(localName = "getJobExportWorkflowFilesResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetJobExportWorkflowFilesResponse")
    public java.lang.String getJobExportWorkflowFiles(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addJobComment", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.AddJobComment")
    @WebMethod
    @ResponseWrapper(localName = "addJobCommentResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.AddJobCommentResponse")
    public java.lang.String addJobComment(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJobStatus", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetJobStatus")
    @WebMethod
    @ResponseWrapper(localName = "getJobStatusResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetJobStatusResponse")
    public java.lang.String getJobStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uploadFileForInitial", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.UploadFileForInitial")
    @WebMethod
    @ResponseWrapper(localName = "uploadFileForInitialResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.UploadFileForInitialResponse")
    public java.lang.String uploadFileForInitial(
        @WebParam(name = "arg0", targetNamespace = "")
        com.globalsight.www.webservices.WrapHashMap arg0
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDownloadableJobs", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetDownloadableJobs")
    @WebMethod
    @ResponseWrapper(localName = "getDownloadableJobsResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetDownloadableJobsResponse")
    public java.lang.String getDownloadableJobs(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws WebServiceException_Exception;

    @RequestWrapper(localName = "createJob", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.CreateJob")
    @WebMethod
    @ResponseWrapper(localName = "createJobResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.CreateJobResponse")
    public void createJob(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    ) throws WebServiceException_Exception;

    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.UploadFile")
    @WebMethod
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.UploadFileResponse")
    public void uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getJobExportFiles", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetJobExportFiles")
    @WebMethod
    @ResponseWrapper(localName = "getJobExportFilesResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetJobExportFilesResponse")
    public java.lang.String getJobExportFiles(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws WebServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUniqueJobName", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetUniqueJobName")
    @WebMethod
    @ResponseWrapper(localName = "getUniqueJobNameResponse", targetNamespace = "http://webservices.globalsight.com/", className = "com.globalsight.www.webservices.GetUniqueJobNameResponse")
    public java.lang.String getUniqueJobName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws WebServiceException_Exception;
}
