/*
 * EditorPnl.java
 *
 * Created on May 4, 2004, 7:58 PM
 */

package debex.ui.view;

/**
 *
 * @author  cvdlaan
 */
public class EditorPnl extends javax.swing.JPanel
{
    
    /** Creates new form EditorPnl */
    public EditorPnl ()
    {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        editorPane = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        resultPane = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Extraction Result:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_save.setMnemonic('S');
        btn_save.setText("Save");
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 70, -1));

        btn_cancel.setMnemonic('C');
        btn_cancel.setText("Cancel");
        add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 70, -1));

        jLabel2.setText("Source Document:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        editorPane.setViewportView(editor);

        add(editorPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 600, 360));

        result.setEditable(false);
        result.setLineWrap(true);
        result.setWrapStyleWord(true);
        resultPane.setViewportView(result);

        add(resultPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 520, 70));

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancel;
    public javax.swing.JButton btn_save;
    public javax.swing.JTextArea editor;
    public javax.swing.JScrollPane editorPane;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JTextArea result;
    public javax.swing.JScrollPane resultPane;
    // End of variables declaration//GEN-END:variables
    
}
