/**
 *  Copyright 2009 Welocalize, Inc. 
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  
 *  You may obtain a copy of the License at 
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  
 */

package debex.ui.view;

public class SplashPnl extends javax.swing.JPanel
{

    /** Creates new form SplashPnl */
    public SplashPnl()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents()//GEN-BEGIN:initComponents
    {
        topPnl = new javax.swing.JPanel();
        lb_extracting = new javax.swing.JLabel();
        prb_progress = new javax.swing.JProgressBar();
        bottomPnl = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 1));

        topPnl.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        lb_extracting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_extracting.setText("Extracting ...");
        topPnl.add(lb_extracting);

        topPnl.add(prb_progress);

        add(topPnl);

        btn_cancel.setMnemonic('c');
        btn_cancel.setText("Cancel");
        bottomPnl.add(btn_cancel);

        add(bottomPnl);

    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bottomPnl;
    public javax.swing.JButton btn_cancel;
    public javax.swing.JLabel lb_extracting;
    public javax.swing.JProgressBar prb_progress;
    public javax.swing.JPanel topPnl;
    // End of variables declaration//GEN-END:variables

}
