锘�//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.6018
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.6018.
// 
namespace WebSvcTester.Ambassador {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AmbassadorWebServiceSoapBinding", Namespace="http://www.globalsight.com/webservices/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(WebServiceException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Vector))]
    public class AmbassadorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AmbassadorService() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["WebSvcTester.Ambassador.AmbassadorService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://dragade:7001/globalsight/services/AmbassadorWebService";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getUserInfoReturn")]
        public string getUserInfo(string in0, string in1) {
            object[] results = this.Invoke("getUserInfo", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUserInfo(string in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUserInfo", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetUserInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("loginReturn")]
        public string login(string in0, string in1) {
            object[] results = this.Invoke("login", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getStatusReturn")]
        public string getStatus(string in0, string in1) {
            object[] results = this.Invoke("getStatus", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetStatus(string in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getStatus", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("isInstalledReturn")]
        public bool isInstalled() {
            object[] results = this.Invoke("isInstalled", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisInstalled(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isInstalled", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndisInstalled(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("cancelJobReturn")]
        public string cancelJob(string in0, string in1) {
            object[] results = this.Invoke("cancelJob", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelJob(string in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelJob", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcancelJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllLocalePairsReturn")]
        public string getAllLocalePairs(string in0) {
            object[] results = this.Invoke("getAllLocalePairs", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllLocalePairs(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllLocalePairs", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllLocalePairs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllProjectsReturn")]
        public string getAllProjects(string in0) {
            object[] results = this.Invoke("getAllProjects", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllProjects(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllProjects", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllProjects(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("cancelWorkflowReturn")]
        public string cancelWorkflow(string in0, string in1, string in2) {
            object[] results = this.Invoke("cancelWorkflow", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelWorkflow(string in0, string in1, string in2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelWorkflow", new object[] {
                        in0,
                        in1,
                        in2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcancelWorkflow(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("addCommentReturn")]
        public string addComment(string in0, long in1, int in2, string in3, string in4, object[] in5, object[] in6) {
            object[] results = this.Invoke("addComment", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddComment(string in0, long in1, int in2, string in3, string in4, object[] in5, object[] in6, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addComment", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndaddComment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("helloWorldReturn")]
        public string helloWorld() {
            object[] results = this.Invoke("helloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginhelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("helloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndhelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getFileProfileInformationReturn")]
        public string getFileProfileInformation(string in0) {
            object[] results = this.Invoke("getFileProfileInformation", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetFileProfileInformation(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getFileProfileInformation", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetFileProfileInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllActivityTypesReturn")]
        public string getAllActivityTypes(string in0) {
            object[] results = this.Invoke("getAllActivityTypes", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllActivityTypes(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllActivityTypes", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllActivityTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllUsersReturn")]
        public string getAllUsers(string in0) {
            object[] results = this.Invoke("getAllUsers", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllUsers(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllUsers", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllProjectsByUserReturn")]
        public string getAllProjectsByUser(string in0) {
            object[] results = this.Invoke("getAllProjectsByUser", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllProjectsByUser(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllProjectsByUser", new object[] {
                        in0}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllProjectsByUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("submitDocumentReturn")]
        public string submitDocument(string in0, string in1, string in2, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] System.Byte[] in3, string in4) {
            object[] results = this.Invoke("submitDocument", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsubmitDocument(string in0, string in1, string in2, System.Byte[] in3, string in4, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("submitDocument", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsubmitDocument(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getLocalizedDocumentsReturn")]
        public string getLocalizedDocuments(string in0, string in1) {
            object[] results = this.Invoke("getLocalizedDocuments", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLocalizedDocuments(string in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLocalizedDocuments", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetLocalizedDocuments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("cancelJobByIdReturn")]
        public string cancelJobById(string in0, long in1) {
            object[] results = this.Invoke("cancelJobById", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelJobById(string in0, long in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelJobById", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcancelJobById(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("exportWorkflowReturn")]
        public string exportWorkflow(string in0, string in1, string in2) {
            object[] results = this.Invoke("exportWorkflow", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexportWorkflow(string in0, string in1, string in2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exportWorkflow", new object[] {
                        in0,
                        in1,
                        in2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexportWorkflow(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("exportJobReturn")]
        public string exportJob(string in0, string in1) {
            object[] results = this.Invoke("exportJob", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginexportJob(string in0, string in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("exportJob", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndexportJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAcceptedTasksInWorkflowReturn")]
        public string getAcceptedTasksInWorkflow(string in0, long in1) {
            object[] results = this.Invoke("getAcceptedTasksInWorkflow", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAcceptedTasksInWorkflow(string in0, long in1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAcceptedTasksInWorkflow", new object[] {
                        in0,
                        in1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAcceptedTasksInWorkflow(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://www.globalsight.com/webservices/", ResponseNamespace="http://www.globalsight.com/webservices/")]
        [return: System.Xml.Serialization.SoapElementAttribute("getTasksInJobReturn")]
        public string getTasksInJob(string in0, long in1, string in2) {
            object[] results = this.Invoke("getTasksInJob", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTasksInJob(string in0, long in1, string in2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTasksInJob", new object[] {
                        in0,
                        in1,
                        in2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetTasksInJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("WebServiceException", "http://webservices.globalsight.com")]
    public class WebServiceException {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("Vector", "http://xml.apache.org/xml-soap")]
    public class Vector {
        
        /// <remarks/>
        public object[] item;
    }
}
