/*************************************************************************
*
* ADOBE CONFIDENTIAL
* __________________
*
* Copyright 1986 - 2005 Adobe Systems Incorporated
* All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains the property
* of Adobe Systems Incorporated and its suppliers, if any. The intellectual
* and technical concepts contained herein are proprietary to Adobe Systems
* Incorporated and its suppliers and may be covered by U.S. and Foreign
* Patents, patents in process, and are protected by trade secret or
* copyright law. Dissemination of this information or reproduction of this
* material is strictly forbidden unless prior written permission is
* obtained from Adobe Systems Incorporated.
**************************************************************************/

/*  Condition macros 		*/
#define MifConditionGetCTag(x) ((x)->CTag)
#define MifConditionSetCTag(x, value) ((x)->CTag=(value))
#define MifConditionGetCState(x) ((x)->CState)
#define MifConditionSetCState(x, value) ((x)->CState=(value))
#define MifConditionGetCStyle(x) ((x)->CStyle)
#define MifConditionSetCStyle(x, value) ((x)->CStyle=(value))
#define MifConditionGetCSeparation(x) ((x)->CSeparation)
#define MifConditionSetCSeparation(x, value) ((x)->CSeparation=(value))

/*  ConditionCatalog macros 		*/
#define MifConditionCatalogGetCondition(x) ((x)->Condition)
#define MifConditionCatalogSetCondition(x, value) ((x)->Condition=(value))

/*  Font macros 		*/
#define MifFontGetFTag(x) ((x)->FTag)
#define MifFontSetFTag(x, value) ((x)->FTag=(value))
#define MifFontGetFFamily(x) ((x)->FFamily)
#define MifFontSetFFamily(x, value) ((x)->FFamily=(value))
#define MifFontGetFVar(x) ((x)->FVar)
#define MifFontSetFVar(x, value) ((x)->FVar=(value))
#define MifFontGetFWeight(x) ((x)->FWeight)
#define MifFontSetFWeight(x, value) ((x)->FWeight=(value))
#define MifFontGetFAngle(x) ((x)->FAngle)
#define MifFontSetFAngle(x, value) ((x)->FAngle=(value))
#define MifFontGetFPlain(x) ((x)->FPlain)
#define MifFontSetFPlain(x, value) ((x)->FPlain=(value))
#define MifFontGetFBold(x) ((x)->FBold)
#define MifFontSetFBold(x, value) ((x)->FBold=(value))
#define MifFontGetFItalic(x) ((x)->FItalic)
#define MifFontSetFItalic(x, value) ((x)->FItalic=(value))
#define MifFontGetFSize(x) ((x)->FSize)
#define MifFontSetFSize(x, value) ((x)->FSize=(value))
#define MifFontGetFUnderline(x) ((x)->FUnderline)
#define MifFontSetFUnderline(x, value) ((x)->FUnderline=(value))
#define MifFontGetFOverline(x) ((x)->FOverline)
#define MifFontSetFOverline(x, value) ((x)->FOverline=(value))
#define MifFontGetFStrike(x) ((x)->FStrike)
#define MifFontSetFStrike(x, value) ((x)->FStrike=(value))
#define MifFontGetFSupScript(x) ((x)->FSupScript)
#define MifFontSetFSupScript(x, value) ((x)->FSupScript=(value))
#define MifFontGetFSubScript(x) ((x)->FSubScript)
#define MifFontSetFSubScript(x, value) ((x)->FSubScript=(value))
#define MifFontGetFChangeBar(x) ((x)->FChangeBar)
#define MifFontSetFChangeBar(x, value) ((x)->FChangeBar=(value))
#define MifFontGetFOutline(x) ((x)->FOutline)
#define MifFontSetFOutline(x, value) ((x)->FOutline=(value))
#define MifFontGetFShadow(x) ((x)->FShadow)
#define MifFontSetFShadow(x, value) ((x)->FShadow=(value))
#define MifFontGetFPairKern(x) ((x)->FPairKern)
#define MifFontSetFPairKern(x, value) ((x)->FPairKern=(value))
#define MifFontGetFDoubleUnderline(x) ((x)->FDoubleUnderline)
#define MifFontSetFDoubleUnderline(x, value) ((x)->FDoubleUnderline=(value))
#define MifFontGetFNumericUnderline(x) ((x)->FNumericUnderline)
#define MifFontSetFNumericUnderline(x, value) ((x)->FNumericUnderline=(value))
#define MifFontGetFDX(x) ((x)->FDX)
#define MifFontSetFDX(x, value) ((x)->FDX=(value))
#define MifFontGetFDY(x) ((x)->FDY)
#define MifFontSetFDY(x, value) ((x)->FDY=(value))
#define MifFontGetFDW(x) ((x)->FDW)
#define MifFontSetFDW(x, value) ((x)->FDW=(value))
#define MifFontGetFSeparation(x) ((x)->FSeparation)
#define MifFontSetFSeparation(x, value) ((x)->FSeparation=(value))
#define MifFontGetFPlain(x) ((x)->FPlain)
#define MifFontSetFPlain(x, value) ((x)->FPlain=(value))
#define MifFontGetFBold(x) ((x)->FBold)
#define MifFontSetFBold(x, value) ((x)->FBold=(value))
#define MifFontGetFItalic(x) ((x)->FItalic)
#define MifFontSetFItalic(x, value) ((x)->FItalic=(value))
#define MifFontGetFColor(x) ((x)->FColor)
#define MifFontSetFColor(x, value) ((x)->FColor=(value))

/*  PgfFont macros 		*/
#define MifPgfFontGetFTag(x) ((x)->FTag)
#define MifPgfFontSetFTag(x, value) ((x)->FTag=(value))
#define MifPgfFontGetFFamily(x) ((x)->FFamily)
#define MifPgfFontSetFFamily(x, value) ((x)->FFamily=(value))
#define MifPgfFontGetFVar(x) ((x)->FVar)
#define MifPgfFontSetFVar(x, value) ((x)->FVar=(value))
#define MifPgfFontGetFWeight(x) ((x)->FWeight)
#define MifPgfFontSetFWeight(x, value) ((x)->FWeight=(value))
#define MifPgfFontGetFAngle(x) ((x)->FAngle)
#define MifPgfFontSetFAngle(x, value) ((x)->FAngle=(value))
#define MifPgfFontGetFPlain(x) ((x)->FPlain)
#define MifPgfFontSetFPlain(x, value) ((x)->FPlain=(value))
#define MifPgfFontGetFBold(x) ((x)->FBold)
#define MifPgfFontSetFBold(x, value) ((x)->FBold=(value))
#define MifPgfFontGetFItalic(x) ((x)->FItalic)
#define MifPgfFontSetFItalic(x, value) ((x)->FItalic=(value))
#define MifPgfFontGetFSize(x) ((x)->FSize)
#define MifPgfFontSetFSize(x, value) ((x)->FSize=(value))
#define MifPgfFontGetFUnderline(x) ((x)->FUnderline)
#define MifPgfFontSetFUnderline(x, value) ((x)->FUnderline=(value))
#define MifPgfFontGetFOverline(x) ((x)->FOverline)
#define MifPgfFontSetFOverline(x, value) ((x)->FOverline=(value))
#define MifPgfFontGetFStrike(x) ((x)->FStrike)
#define MifPgfFontSetFStrike(x, value) ((x)->FStrike=(value))
#define MifPgfFontGetFSupScript(x) ((x)->FSupScript)
#define MifPgfFontSetFSupScript(x, value) ((x)->FSupScript=(value))
#define MifPgfFontGetFSubScript(x) ((x)->FSubScript)
#define MifPgfFontSetFSubScript(x, value) ((x)->FSubScript=(value))
#define MifPgfFontGetFChangeBar(x) ((x)->FChangeBar)
#define MifPgfFontSetFChangeBar(x, value) ((x)->FChangeBar=(value))
#define MifPgfFontGetFOutline(x) ((x)->FOutline)
#define MifPgfFontSetFOutline(x, value) ((x)->FOutline=(value))
#define MifPgfFontGetFShadow(x) ((x)->FShadow)
#define MifPgfFontSetFShadow(x, value) ((x)->FShadow=(value))
#define MifPgfFontGetFPairKern(x) ((x)->FPairKern)
#define MifPgfFontSetFPairKern(x, value) ((x)->FPairKern=(value))
#define MifPgfFontGetFDoubleUnderline(x) ((x)->FDoubleUnderline)
#define MifPgfFontSetFDoubleUnderline(x, value) ((x)->FDoubleUnderline=(value))
#define MifPgfFontGetFNumericUnderline(x) ((x)->FNumericUnderline)
#define MifPgfFontSetFNumericUnderline(x, value) ((x)->FNumericUnderline=(value))
#define MifPgfFontGetFDX(x) ((x)->FDX)
#define MifPgfFontSetFDX(x, value) ((x)->FDX=(value))
#define MifPgfFontGetFDY(x) ((x)->FDY)
#define MifPgfFontSetFDY(x, value) ((x)->FDY=(value))
#define MifPgfFontGetFDW(x) ((x)->FDW)
#define MifPgfFontSetFDW(x, value) ((x)->FDW=(value))
#define MifPgfFontGetFSeparation(x) ((x)->FSeparation)
#define MifPgfFontSetFSeparation(x, value) ((x)->FSeparation=(value))
#define MifPgfFontGetFPlain(x) ((x)->FPlain)
#define MifPgfFontSetFPlain(x, value) ((x)->FPlain=(value))
#define MifPgfFontGetFBold(x) ((x)->FBold)
#define MifPgfFontSetFBold(x, value) ((x)->FBold=(value))
#define MifPgfFontGetFItalic(x) ((x)->FItalic)
#define MifPgfFontSetFItalic(x, value) ((x)->FItalic=(value))
#define MifPgfFontGetFColor(x) ((x)->FColor)
#define MifPgfFontSetFColor(x, value) ((x)->FColor=(value))

/*  XRef macros 		*/
#define MifXRefGetXRefName(x) ((x)->XRefName)
#define MifXRefSetXRefName(x, value) ((x)->XRefName=(value))
#define MifXRefGetXRefSrcText(x) ((x)->XRefSrcText)
#define MifXRefSetXRefSrcText(x, value) ((x)->XRefSrcText=(value))
#define MifXRefGetXRefSrcFile(x) ((x)->XRefSrcFile)
#define MifXRefSetXRefSrcFile(x, value) ((x)->XRefSrcFile=(value))

/*  Marker macros 		*/
#define MifMarkerGetMType(x) ((x)->MType)
#define MifMarkerSetMType(x, value) ((x)->MType=(value))
#define MifMarkerGetMText(x) ((x)->MText)
#define MifMarkerSetMText(x, value) ((x)->MText=(value))
#define MifMarkerGetMCurrPage(x) ((x)->MCurrPage)
#define MifMarkerSetMCurrPage(x, value) ((x)->MCurrPage=(value))

/*  Conditional macros 		*/
#define MifConditionalGetInCondition(x) ((x)->InCondition)
#define MifConditionalSetInCondition(x, value) ((x)->InCondition=(value))
#define MifInConditionListGetNext(x) ((x)->Next)
#define MifInConditionListSetNext(x, value) ((x)->Next=(value))
#define MifInConditionListGetPrev(x) ((x)->Prev)
#define MifInConditionListSetPrev(x, value) ((x)->Prev=(value))
#define MifInConditionListGetInCondition(x) ((x)->InCondition)
#define MifInConditionListSetInCondition(x, value) ((x)->InCondition=(value))

/*  Variable macros 		*/
#define MifVariableGetVariableName(x) ((x)->VariableName)
#define MifVariableSetVariableName(x, value) ((x)->VariableName=(value))

/*  ParaLine macros 		*/
#define MifParaLineGetTextRectID(x) ((x)->TextRectID)
#define MifParaLineSetTextRectID(x, value) ((x)->TextRectID=(value))
#define MifParaLineGetSpclHyphenation(x) ((x)->SpclHyphenation)
#define MifParaLineSetSpclHyphenation(x, value) ((x)->SpclHyphenation=(value))
#define MifParaLineGetLineItems(x) ((x)->LineItems)
#define MifParaLineSetLineItems(x, value) ((x)->LineItems=(value))
#define MifParaLineGetFont(x) ((x)->Font)
#define MifParaLineSetFont(x, value) ((x)->Font=(value))
#define MifParaLineGetConditional(x) ((x)->Conditional)
#define MifParaLineSetConditional(x, value) ((x)->Conditional=(value))
#define MifParaLineGetUnconditional(x) ((x)->Unconditional)
#define MifParaLineSetUnconditional(x, value) ((x)->Unconditional=(value))
#define MifParaLineGetString(x) ((x)->String)
#define MifParaLineSetString(x, value) ((x)->String=(value))
#define MifParaLineGetChar(x) ((x)->Char)
#define MifParaLineSetChar(x, value) ((x)->Char=(value))
#define MifParaLineGetATbl(x) ((x)->ATbl)
#define MifParaLineSetATbl(x, value) ((x)->ATbl=(value))
#define MifParaLineGetAFrame(x) ((x)->AFrame)
#define MifParaLineSetAFrame(x, value) ((x)->AFrame=(value))
#define MifParaLineGetFNote(x) ((x)->FNote)
#define MifParaLineSetFNote(x, value) ((x)->FNote=(value))
#define MifParaLineGetMarker(x) ((x)->Marker)
#define MifParaLineSetMarker(x, value) ((x)->Marker=(value))
#define MifParaLineGetVariable(x) ((x)->Variable)
#define MifParaLineSetVariable(x, value) ((x)->Variable=(value))
#define MifParaLineGetXRef(x) ((x)->XRef)
#define MifParaLineSetXRef(x, value) ((x)->XRef=(value))
#define MifParaLineGetXRefEnd(x) ((x)->XRefEnd)
#define MifParaLineSetXRefEnd(x, value) ((x)->XRefEnd=(value))
#define MifUnconditionalListGetNext(x) ((x)->Next)
#define MifUnconditionalListSetNext(x, value) ((x)->Next=(value))
#define MifUnconditionalListGetPrev(x) ((x)->Prev)
#define MifUnconditionalListSetPrev(x, value) ((x)->Prev=(value))
#define MifUnconditionalListGetUnconditional(x) ((x)->Unconditional)
#define MifUnconditionalListSetUnconditional(x, value) ((x)->Unconditional=(value))
#define MifStringListGetNext(x) ((x)->Next)
#define MifStringListSetNext(x, value) ((x)->Next=(value))
#define MifStringListGetPrev(x) ((x)->Prev)
#define MifStringListSetPrev(x, value) ((x)->Prev=(value))
#define MifStringListGetString(x) ((x)->String)
#define MifStringListSetString(x, value) ((x)->String=(value))
#define MifCharListGetNext(x) ((x)->Next)
#define MifCharListSetNext(x, value) ((x)->Next=(value))
#define MifCharListGetPrev(x) ((x)->Prev)
#define MifCharListSetPrev(x, value) ((x)->Prev=(value))
#define MifCharListGetChar(x) ((x)->Char)
#define MifCharListSetChar(x, value) ((x)->Char=(value))
#define MifATblListGetNext(x) ((x)->Next)
#define MifATblListSetNext(x, value) ((x)->Next=(value))
#define MifATblListGetPrev(x) ((x)->Prev)
#define MifATblListSetPrev(x, value) ((x)->Prev=(value))
#define MifATblListGetATbl(x) ((x)->ATbl)
#define MifATblListSetATbl(x, value) ((x)->ATbl=(value))
#define MifAFrameListGetNext(x) ((x)->Next)
#define MifAFrameListSetNext(x, value) ((x)->Next=(value))
#define MifAFrameListGetPrev(x) ((x)->Prev)
#define MifAFrameListSetPrev(x, value) ((x)->Prev=(value))
#define MifAFrameListGetAFrame(x) ((x)->AFrame)
#define MifAFrameListSetAFrame(x, value) ((x)->AFrame=(value))
#define MifFNoteListGetNext(x) ((x)->Next)
#define MifFNoteListSetNext(x, value) ((x)->Next=(value))
#define MifFNoteListGetPrev(x) ((x)->Prev)
#define MifFNoteListSetPrev(x, value) ((x)->Prev=(value))
#define MifFNoteListGetFNote(x) ((x)->FNote)
#define MifFNoteListSetFNote(x, value) ((x)->FNote=(value))
#define MifXRefEndListGetNext(x) ((x)->Next)
#define MifXRefEndListSetNext(x, value) ((x)->Next=(value))
#define MifXRefEndListGetPrev(x) ((x)->Prev)
#define MifXRefEndListSetPrev(x, value) ((x)->Prev=(value))
#define MifXRefEndListGetXRefEnd(x) ((x)->XRefEnd)
#define MifXRefEndListSetXRefEnd(x, value) ((x)->XRefEnd=(value))

/*  TabStop macros 		*/
#define MifTabStopGetTSX(x) ((x)->TSX)
#define MifTabStopSetTSX(x, value) ((x)->TSX=(value))
#define MifTabStopGetTSType(x) ((x)->TSType)
#define MifTabStopSetTSType(x, value) ((x)->TSType=(value))
#define MifTabStopGetTSLeaderStr(x) ((x)->TSLeaderStr)
#define MifTabStopSetTSLeaderStr(x, value) ((x)->TSLeaderStr=(value))
#define MifTabStopGetTSDecimalChar(x) ((x)->TSDecimalChar)
#define MifTabStopSetTSDecimalChar(x, value) ((x)->TSDecimalChar=(value))

/*  Pgf macros 		*/
#define MifPgfGetPgfTag(x) ((x)->PgfTag)
#define MifPgfSetPgfTag(x, value) ((x)->PgfTag=(value))
#define MifPgfGetPgfUseNextTag(x) ((x)->PgfUseNextTag)
#define MifPgfSetPgfUseNextTag(x, value) ((x)->PgfUseNextTag=(value))
#define MifPgfGetPgfNextTag(x) ((x)->PgfNextTag)
#define MifPgfSetPgfNextTag(x, value) ((x)->PgfNextTag=(value))
#define MifPgfGetPgfAlignment(x) ((x)->PgfAlignment)
#define MifPgfSetPgfAlignment(x, value) ((x)->PgfAlignment=(value))
#define MifPgfGetPgfFIndent(x) ((x)->PgfFIndent)
#define MifPgfSetPgfFIndent(x, value) ((x)->PgfFIndent=(value))
#define MifPgfGetPgfLIndent(x) ((x)->PgfLIndent)
#define MifPgfSetPgfLIndent(x, value) ((x)->PgfLIndent=(value))
#define MifPgfGetPgfRIndent(x) ((x)->PgfRIndent)
#define MifPgfSetPgfRIndent(x, value) ((x)->PgfRIndent=(value))
#define MifPgfGetPgfTopSeparator(x) ((x)->PgfTopSeparator)
#define MifPgfSetPgfTopSeparator(x, value) ((x)->PgfTopSeparator=(value))
#define MifPgfGetPgfBotSeparator(x) ((x)->PgfBotSeparator)
#define MifPgfSetPgfBotSeparator(x, value) ((x)->PgfBotSeparator=(value))
#define MifPgfGetPgfPlacement(x) ((x)->PgfPlacement)
#define MifPgfSetPgfPlacement(x, value) ((x)->PgfPlacement=(value))
#define MifPgfGetPgfSpBefore(x) ((x)->PgfSpBefore)
#define MifPgfSetPgfSpBefore(x, value) ((x)->PgfSpBefore=(value))
#define MifPgfGetPgfSpAfter(x) ((x)->PgfSpAfter)
#define MifPgfSetPgfSpAfter(x, value) ((x)->PgfSpAfter=(value))
#define MifPgfGetPgfWithPrev(x) ((x)->PgfWithPrev)
#define MifPgfSetPgfWithPrev(x, value) ((x)->PgfWithPrev=(value))
#define MifPgfGetPgfWithNext(x) ((x)->PgfWithNext)
#define MifPgfSetPgfWithNext(x, value) ((x)->PgfWithNext=(value))
#define MifPgfGetPgfBlockSize(x) ((x)->PgfBlockSize)
#define MifPgfSetPgfBlockSize(x, value) ((x)->PgfBlockSize=(value))
#define MifPgfGetPgfFont(x) ((x)->PgfFont)
#define MifPgfSetPgfFont(x, value) ((x)->PgfFont=(value))
#define MifPgfGetPgfLineSpacing(x) ((x)->PgfLineSpacing)
#define MifPgfSetPgfLineSpacing(x, value) ((x)->PgfLineSpacing=(value))
#define MifPgfGetPgfLeading(x) ((x)->PgfLeading)
#define MifPgfSetPgfLeading(x, value) ((x)->PgfLeading=(value))
#define MifPgfGetPgfAutoNum(x) ((x)->PgfAutoNum)
#define MifPgfSetPgfAutoNum(x, value) ((x)->PgfAutoNum=(value))
#define MifPgfGetPgfNumFormat(x) ((x)->PgfNumFormat)
#define MifPgfSetPgfNumFormat(x, value) ((x)->PgfNumFormat=(value))
#define MifPgfGetPgfNumberFont(x) ((x)->PgfNumberFont)
#define MifPgfSetPgfNumberFont(x, value) ((x)->PgfNumberFont=(value))
#define MifPgfGetPgfNumAtEnd(x) ((x)->PgfNumAtEnd)
#define MifPgfSetPgfNumAtEnd(x, value) ((x)->PgfNumAtEnd=(value))
#define MifPgfGetPgfNumTabs(x) ((x)->PgfNumTabs)
#define MifPgfSetPgfNumTabs(x, value) ((x)->PgfNumTabs=(value))
#define MifPgfGetTabStop(x) ((x)->TabStop)
#define MifPgfSetTabStop(x, value) ((x)->TabStop=(value))
#define MifPgfGetPgfHyphenate(x) ((x)->PgfHyphenate)
#define MifPgfSetPgfHyphenate(x, value) ((x)->PgfHyphenate=(value))
#define MifPgfGetHyphenMaxLines(x) ((x)->HyphenMaxLines)
#define MifPgfSetHyphenMaxLines(x, value) ((x)->HyphenMaxLines=(value))
#define MifPgfGetHyphenMinPrefix(x) ((x)->HyphenMinPrefix)
#define MifPgfSetHyphenMinPrefix(x, value) ((x)->HyphenMinPrefix=(value))
#define MifPgfGetHyphenMinSuffix(x) ((x)->HyphenMinSuffix)
#define MifPgfSetHyphenMinSuffix(x, value) ((x)->HyphenMinSuffix=(value))
#define MifPgfGetHyphenMinWord(x) ((x)->HyphenMinWord)
#define MifPgfSetHyphenMinWord(x, value) ((x)->HyphenMinWord=(value))
#define MifPgfGetPgfLetterSpace(x) ((x)->PgfLetterSpace)
#define MifPgfSetPgfLetterSpace(x, value) ((x)->PgfLetterSpace=(value))
#define MifPgfGetPgfMinWordSpace(x) ((x)->PgfMinWordSpace)
#define MifPgfSetPgfMinWordSpace(x, value) ((x)->PgfMinWordSpace=(value))
#define MifPgfGetPgfOptWordSpace(x) ((x)->PgfOptWordSpace)
#define MifPgfSetPgfOptWordSpace(x, value) ((x)->PgfOptWordSpace=(value))
#define MifPgfGetPgfMaxWordSpace(x) ((x)->PgfMaxWordSpace)
#define MifPgfSetPgfMaxWordSpace(x, value) ((x)->PgfMaxWordSpace=(value))
#define MifPgfGetPgfLanguage(x) ((x)->PgfLanguage)
#define MifPgfSetPgfLanguage(x, value) ((x)->PgfLanguage=(value))
#define MifPgfGetPgfCellAlignment(x) ((x)->PgfCellAlignment)
#define MifPgfSetPgfCellAlignment(x, value) ((x)->PgfCellAlignment=(value))
#define MifPgfGetPgfCellMargins(x) ((x)->PgfCellMargins)
#define MifPgfSetPgfCellMargins(x, value) ((x)->PgfCellMargins=(value))
#define MifPgfGetPgfCellLMarginFixed(x) ((x)->PgfCellLMarginFixed)
#define MifPgfSetPgfCellLMarginFixed(x, value) ((x)->PgfCellLMarginFixed=(value))
#define MifPgfGetPgfCellTMarginFixed(x) ((x)->PgfCellTMarginFixed)
#define MifPgfSetPgfCellTMarginFixed(x, value) ((x)->PgfCellTMarginFixed=(value))
#define MifPgfGetPgfCellRMarginFixed(x) ((x)->PgfCellRMarginFixed)
#define MifPgfSetPgfCellRMarginFixed(x, value) ((x)->PgfCellRMarginFixed=(value))
#define MifPgfGetPgfCellBMarginFixed(x) ((x)->PgfCellBMarginFixed)
#define MifPgfSetPgfCellBMarginFixed(x, value) ((x)->PgfCellBMarginFixed=(value))

/*  PgfCatalog macros 		*/
#define MifPgfCatalogGetUnits(x) ((x)->Units)
#define MifPgfCatalogSetUnits(x, value) ((x)->Units=(value))
#define MifPgfCatalogGetVerbose(x) ((x)->Verbose)
#define MifPgfCatalogSetVerbose(x, value) ((x)->Verbose=(value))
#define MifPgfCatalogGetPgf(x) ((x)->Pgf)
#define MifPgfCatalogSetPgf(x, value) ((x)->Pgf=(value))

/*  FontCatalog macros 		*/
#define MifFontCatalogGetUnits(x) ((x)->Units)
#define MifFontCatalogSetUnits(x, value) ((x)->Units=(value))
#define MifFontCatalogGetVerbose(x) ((x)->Verbose)
#define MifFontCatalogSetVerbose(x, value) ((x)->Verbose=(value))
#define MifFontCatalogGetFont(x) ((x)->Font)
#define MifFontCatalogSetFont(x, value) ((x)->Font=(value))

/*  Ruling macros 		*/
#define MifRulingGetRulingTag(x) ((x)->RulingTag)
#define MifRulingSetRulingTag(x, value) ((x)->RulingTag=(value))
#define MifRulingGetRulingPenWidth(x) ((x)->RulingPenWidth)
#define MifRulingSetRulingPenWidth(x, value) ((x)->RulingPenWidth=(value))
#define MifRulingGetRulingGap(x) ((x)->RulingGap)
#define MifRulingSetRulingGap(x, value) ((x)->RulingGap=(value))
#define MifRulingGetRulingSeparation(x) ((x)->RulingSeparation)
#define MifRulingSetRulingSeparation(x, value) ((x)->RulingSeparation=(value))
#define MifRulingGetRulingPen(x) ((x)->RulingPen)
#define MifRulingSetRulingPen(x, value) ((x)->RulingPen=(value))
#define MifRulingGetRulingLines(x) ((x)->RulingLines)
#define MifRulingSetRulingLines(x, value) ((x)->RulingLines=(value))

/*  RulingCatalog macros 		*/
#define MifRulingCatalogGetRuling(x) ((x)->Ruling)
#define MifRulingCatalogSetRuling(x, value) ((x)->Ruling=(value))

/*  TblColumnH macros 		*/
#define MifTblColumnHGetPgfTag(x) ((x)->PgfTag)
#define MifTblColumnHSetPgfTag(x, value) ((x)->PgfTag=(value))
#define MifTblColumnHGetPgf(x) ((x)->Pgf)
#define MifTblColumnHSetPgf(x, value) ((x)->Pgf=(value))

/*  TblColumnBody macros 		*/
#define MifTblColumnBodyGetPgfTag(x) ((x)->PgfTag)
#define MifTblColumnBodySetPgfTag(x, value) ((x)->PgfTag=(value))
#define MifTblColumnBodyGetPgf(x) ((x)->Pgf)
#define MifTblColumnBodySetPgf(x, value) ((x)->Pgf=(value))

/*  TblColumnF macros 		*/
#define MifTblColumnFGetPgfTag(x) ((x)->PgfTag)
#define MifTblColumnFSetPgfTag(x, value) ((x)->PgfTag=(value))
#define MifTblColumnFGetPgf(x) ((x)->Pgf)
#define MifTblColumnFSetPgf(x, value) ((x)->Pgf=(value))

/*  TblColumn macros 		*/
#define MifTblColumnGetTblColumnNum(x) ((x)->TblColumnNum)
#define MifTblColumnSetTblColumnNum(x, value) ((x)->TblColumnNum=(value))
#define MifTblColumnGetTblColumnWidth(x) ((x)->TblColumnWidth)
#define MifTblColumnSetTblColumnWidth(x, value) ((x)->TblColumnWidth=(value))
#define MifTblColumnGetTblColumnH(x) ((x)->TblColumnH)
#define MifTblColumnSetTblColumnH(x, value) ((x)->TblColumnH=(value))
#define MifTblColumnGetTblColumnBody(x) ((x)->TblColumnBody)
#define MifTblColumnSetTblColumnBody(x, value) ((x)->TblColumnBody=(value))
#define MifTblColumnGetTblColumnF(x) ((x)->TblColumnF)
#define MifTblColumnSetTblColumnF(x, value) ((x)->TblColumnF=(value))

/*  TblTitlePgf1 macros 		*/
#define MifTblTitlePgf1GetPgfTag(x) ((x)->PgfTag)
#define MifTblTitlePgf1SetPgfTag(x, value) ((x)->PgfTag=(value))
#define MifTblTitlePgf1GetPgf(x) ((x)->Pgf)
#define MifTblTitlePgf1SetPgf(x, value) ((x)->Pgf=(value))

/*  TblFormat macros 		*/
#define MifTblFormatGetTblTag(x) ((x)->TblTag)
#define MifTblFormatSetTblTag(x, value) ((x)->TblTag=(value))
#define MifTblFormatGetTblWidth(x) ((x)->TblWidth)
#define MifTblFormatSetTblWidth(x, value) ((x)->TblWidth=(value))
#define MifTblFormatGetTblColumn(x) ((x)->TblColumn)
#define MifTblFormatSetTblColumn(x, value) ((x)->TblColumn=(value))
#define MifTblFormatGetTblCellMargins(x) ((x)->TblCellMargins)
#define MifTblFormatSetTblCellMargins(x, value) ((x)->TblCellMargins=(value))
#define MifTblFormatGetTblLIndent(x) ((x)->TblLIndent)
#define MifTblFormatSetTblLIndent(x, value) ((x)->TblLIndent=(value))
#define MifTblFormatGetTblRIndent(x) ((x)->TblRIndent)
#define MifTblFormatSetTblRIndent(x, value) ((x)->TblRIndent=(value))
#define MifTblFormatGetTblAlignment(x) ((x)->TblAlignment)
#define MifTblFormatSetTblAlignment(x, value) ((x)->TblAlignment=(value))
#define MifTblFormatGetTblPlacement(x) ((x)->TblPlacement)
#define MifTblFormatSetTblPlacement(x, value) ((x)->TblPlacement=(value))
#define MifTblFormatGetTblSpBefore(x) ((x)->TblSpBefore)
#define MifTblFormatSetTblSpBefore(x, value) ((x)->TblSpBefore=(value))
#define MifTblFormatGetTblSpAfter(x) ((x)->TblSpAfter)
#define MifTblFormatSetTblSpAfter(x, value) ((x)->TblSpAfter=(value))
#define MifTblFormatGetTblBlockSize(x) ((x)->TblBlockSize)
#define MifTblFormatSetTblBlockSize(x, value) ((x)->TblBlockSize=(value))
#define MifTblFormatGetTblHFFill(x) ((x)->TblHFFill)
#define MifTblFormatSetTblHFFill(x, value) ((x)->TblHFFill=(value))
#define MifTblFormatGetTblHFSeparation(x) ((x)->TblHFSeparation)
#define MifTblFormatSetTblHFSeparation(x, value) ((x)->TblHFSeparation=(value))
#define MifTblFormatGetTblBodyFill(x) ((x)->TblBodyFill)
#define MifTblFormatSetTblBodyFill(x, value) ((x)->TblBodyFill=(value))
#define MifTblFormatGetTblBodySeparation(x) ((x)->TblBodySeparation)
#define MifTblFormatSetTblBodySeparation(x, value) ((x)->TblBodySeparation=(value))
#define MifTblFormatGetTblShadeByColumn(x) ((x)->TblShadeByColumn)
#define MifTblFormatSetTblShadeByColumn(x, value) ((x)->TblShadeByColumn=(value))
#define MifTblFormatGetTblShadePeriod(x) ((x)->TblShadePeriod)
#define MifTblFormatSetTblShadePeriod(x, value) ((x)->TblShadePeriod=(value))
#define MifTblFormatGetTblXFill(x) ((x)->TblXFill)
#define MifTblFormatSetTblXFill(x, value) ((x)->TblXFill=(value))
#define MifTblFormatGetTblXSeparation(x) ((x)->TblXSeparation)
#define MifTblFormatSetTblXSeparation(x, value) ((x)->TblXSeparation=(value))
#define MifTblFormatGetTblAltShadePeriod(x) ((x)->TblAltShadePeriod)
#define MifTblFormatSetTblAltShadePeriod(x, value) ((x)->TblAltShadePeriod=(value))
#define MifTblFormatGetTblLRuling(x) ((x)->TblLRuling)
#define MifTblFormatSetTblLRuling(x, value) ((x)->TblLRuling=(value))
#define MifTblFormatGetTblBRuling(x) ((x)->TblBRuling)
#define MifTblFormatSetTblBRuling(x, value) ((x)->TblBRuling=(value))
#define MifTblFormatGetTblRRuling(x) ((x)->TblRRuling)
#define MifTblFormatSetTblRRuling(x, value) ((x)->TblRRuling=(value))
#define MifTblFormatGetTblTRuling(x) ((x)->TblTRuling)
#define MifTblFormatSetTblTRuling(x, value) ((x)->TblTRuling=(value))
#define MifTblFormatGetTblColumnRuling(x) ((x)->TblColumnRuling)
#define MifTblFormatSetTblColumnRuling(x, value) ((x)->TblColumnRuling=(value))
#define MifTblFormatGetTblXColumnNum(x) ((x)->TblXColumnNum)
#define MifTblFormatSetTblXColumnNum(x, value) ((x)->TblXColumnNum=(value))
#define MifTblFormatGetTblXColumnRuling(x) ((x)->TblXColumnRuling)
#define MifTblFormatSetTblXColumnRuling(x, value) ((x)->TblXColumnRuling=(value))
#define MifTblFormatGetTblBodyRowRuling(x) ((x)->TblBodyRowRuling)
#define MifTblFormatSetTblBodyRowRuling(x, value) ((x)->TblBodyRowRuling=(value))
#define MifTblFormatGetTblXRowRuling(x) ((x)->TblXRowRuling)
#define MifTblFormatSetTblXRowRuling(x, value) ((x)->TblXRowRuling=(value))
#define MifTblFormatGetTblRulingPeriod(x) ((x)->TblRulingPeriod)
#define MifTblFormatSetTblRulingPeriod(x, value) ((x)->TblRulingPeriod=(value))
#define MifTblFormatGetTblHFRowRuling(x) ((x)->TblHFRowRuling)
#define MifTblFormatSetTblHFRowRuling(x, value) ((x)->TblHFRowRuling=(value))
#define MifTblFormatGetTblSeparatorRuling(x) ((x)->TblSeparatorRuling)
#define MifTblFormatSetTblSeparatorRuling(x, value) ((x)->TblSeparatorRuling=(value))
#define MifTblFormatGetTblLastBRuling(x) ((x)->TblLastBRuling)
#define MifTblFormatSetTblLastBRuling(x, value) ((x)->TblLastBRuling=(value))
#define MifTblFormatGetTblTitlePlacement(x) ((x)->TblTitlePlacement)
#define MifTblFormatSetTblTitlePlacement(x, value) ((x)->TblTitlePlacement=(value))
#define MifTblFormatGetTblTitlePgf1(x) ((x)->TblTitlePgf1)
#define MifTblFormatSetTblTitlePgf1(x, value) ((x)->TblTitlePgf1=(value))
#define MifTblFormatGetTblTitleGap(x) ((x)->TblTitleGap)
#define MifTblFormatSetTblTitleGap(x, value) ((x)->TblTitleGap=(value))
#define MifTblFormatGetTblInitNumColumns(x) ((x)->TblInitNumColumns)
#define MifTblFormatSetTblInitNumColumns(x, value) ((x)->TblInitNumColumns=(value))
#define MifTblFormatGetTblInitNumHRows(x) ((x)->TblInitNumHRows)
#define MifTblFormatSetTblInitNumHRows(x, value) ((x)->TblInitNumHRows=(value))
#define MifTblFormatGetTblInitNumBodyRows(x) ((x)->TblInitNumBodyRows)
#define MifTblFormatSetTblInitNumBodyRows(x, value) ((x)->TblInitNumBodyRows=(value))
#define MifTblFormatGetTblInitNumFRows(x) ((x)->TblInitNumFRows)
#define MifTblFormatSetTblInitNumFRows(x, value) ((x)->TblInitNumFRows=(value))
#define MifTblFormatGetTblNumByColumn(x) ((x)->TblNumByColumn)
#define MifTblFormatSetTblNumByColumn(x, value) ((x)->TblNumByColumn=(value))

/*  TblCatalog macros 		*/
#define MifTblCatalogGetTblFormat(x) ((x)->TblFormat)
#define MifTblCatalogSetTblFormat(x, value) ((x)->TblFormat=(value))

/*  VariableFormat macros 		*/
#define MifVariableFormatGetVariableName(x) ((x)->VariableName)
#define MifVariableFormatSetVariableName(x, value) ((x)->VariableName=(value))
#define MifVariableFormatGetVariableDef(x) ((x)->VariableDef)
#define MifVariableFormatSetVariableDef(x, value) ((x)->VariableDef=(value))

/*  VariableFormats macros 		*/
#define MifVariableFormatsGetVariableFormat(x) ((x)->VariableFormat)
#define MifVariableFormatsSetVariableFormat(x, value) ((x)->VariableFormat=(value))

/*  XRefFormat macros 		*/
#define MifXRefFormatGetXRefName(x) ((x)->XRefName)
#define MifXRefFormatSetXRefName(x, value) ((x)->XRefName=(value))
#define MifXRefFormatGetXRefDef(x) ((x)->XRefDef)
#define MifXRefFormatSetXRefDef(x, value) ((x)->XRefDef=(value))

/*  XRefFormats macros 		*/
#define MifXRefFormatsGetXRefFormat(x) ((x)->XRefFormat)
#define MifXRefFormatsSetXRefFormat(x, value) ((x)->XRefFormat=(value))

/*  Document macros 		*/
#define MifDocumentGetDWindowRect(x) ((x)->DWindowRect)
#define MifDocumentSetDWindowRect(x, value) ((x)->DWindowRect=(value))
#define MifDocumentGetDPageSize(x) ((x)->DPageSize)
#define MifDocumentSetDPageSize(x, value) ((x)->DPageSize=(value))
#define MifDocumentGetDStartPage(x) ((x)->DStartPage)
#define MifDocumentSetDStartPage(x, value) ((x)->DStartPage=(value))
#define MifDocumentGetDPageNumStyle(x) ((x)->DPageNumStyle)
#define MifDocumentSetDPageNumStyle(x, value) ((x)->DPageNumStyle=(value))
#define MifDocumentGetDPagePointStyle(x) ((x)->DPagePointStyle)
#define MifDocumentSetDPagePointStyle(x, value) ((x)->DPagePointStyle=(value))
#define MifDocumentGetDTwoSides(x) ((x)->DTwoSides)
#define MifDocumentSetDTwoSides(x, value) ((x)->DTwoSides=(value))
#define MifDocumentGetDParity(x) ((x)->DParity)
#define MifDocumentSetDParity(x, value) ((x)->DParity=(value))
#define MifDocumentGetDPageRounding(x) ((x)->DPageRounding)
#define MifDocumentSetDPageRounding(x, value) ((x)->DPageRounding=(value))
#define MifDocumentGetDFrozenPages(x) ((x)->DFrozenPages)
#define MifDocumentSetDFrozenPages(x, value) ((x)->DFrozenPages=(value))
#define MifDocumentGetDSmartQuotesOn(x) ((x)->DSmartQuotesOn)
#define MifDocumentSetDSmartQuotesOn(x, value) ((x)->DSmartQuotesOn=(value))
#define MifDocumentGetDSmartSpacesOn(x) ((x)->DSmartSpacesOn)
#define MifDocumentSetDSmartSpacesOn(x, value) ((x)->DSmartSpacesOn=(value))
#define MifDocumentGetDLinebreakChars(x) ((x)->DLinebreakChars)
#define MifDocumentSetDLinebreakChars(x, value) ((x)->DLinebreakChars=(value))
#define MifDocumentGetDMaxInterLine(x) ((x)->DMaxInterLine)
#define MifDocumentSetDMaxInterLine(x, value) ((x)->DMaxInterLine=(value))
#define MifDocumentGetDMaxInterPgf(x) ((x)->DMaxInterPgf)
#define MifDocumentSetDMaxInterPgf(x, value) ((x)->DMaxInterPgf=(value))
#define MifDocumentGetDShowAllConditions(x) ((x)->DShowAllConditions)
#define MifDocumentSetDShowAllConditions(x, value) ((x)->DShowAllConditions=(value))
#define MifDocumentGetDDisplayOverrides(x) ((x)->DDisplayOverrides)
#define MifDocumentSetDDisplayOverrides(x, value) ((x)->DDisplayOverrides=(value))
#define MifDocumentGetDFNoteTag(x) ((x)->DFNoteTag)
#define MifDocumentSetDFNoteTag(x, value) ((x)->DFNoteTag=(value))
#define MifDocumentGetDFNoteMaxH(x) ((x)->DFNoteMaxH)
#define MifDocumentSetDFNoteMaxH(x, value) ((x)->DFNoteMaxH=(value))
#define MifDocumentGetDFNoteRestart(x) ((x)->DFNoteRestart)
#define MifDocumentSetDFNoteRestart(x, value) ((x)->DFNoteRestart=(value))
#define MifDocumentGetFNoteStartNum(x) ((x)->FNoteStartNum)
#define MifDocumentSetFNoteStartNum(x, value) ((x)->FNoteStartNum=(value))
#define MifDocumentGetDFNoteNumStyle(x) ((x)->DFNoteNumStyle)
#define MifDocumentSetDFNoteNumStyle(x, value) ((x)->DFNoteNumStyle=(value))
#define MifDocumentGetDFNoteLabels(x) ((x)->DFNoteLabels)
#define MifDocumentSetDFNoteLabels(x, value) ((x)->DFNoteLabels=(value))
#define MifDocumentGetDFNoteAnchorPos(x) ((x)->DFNoteAnchorPos)
#define MifDocumentSetDFNoteAnchorPos(x, value) ((x)->DFNoteAnchorPos=(value))
#define MifDocumentGetDFNoteNumberPos(x) ((x)->DFNoteNumberPos)
#define MifDocumentSetDFNoteNumberPos(x, value) ((x)->DFNoteNumberPos=(value))
#define MifDocumentGetDFNoteAnchorPrefix(x) ((x)->DFNoteAnchorPrefix)
#define MifDocumentSetDFNoteAnchorPrefix(x, value) ((x)->DFNoteAnchorPrefix=(value))
#define MifDocumentGetDFNoteAnchorSuffix(x) ((x)->DFNoteAnchorSuffix)
#define MifDocumentSetDFNoteAnchorSuffix(x, value) ((x)->DFNoteAnchorSuffix=(value))
#define MifDocumentGetDFNoteNumberPrefix(x) ((x)->DFNoteNumberPrefix)
#define MifDocumentSetDFNoteNumberPrefix(x, value) ((x)->DFNoteNumberPrefix=(value))
#define MifDocumentGetDFNoteNumberSuffix(x) ((x)->DFNoteNumberSuffix)
#define MifDocumentSetDFNoteNumberSuffix(x, value) ((x)->DFNoteNumberSuffix=(value))
#define MifDocumentGetDTblFNoteTag(x) ((x)->DTblFNoteTag)
#define MifDocumentSetDTblFNoteTag(x, value) ((x)->DTblFNoteTag=(value))
#define MifDocumentGetDTblFNoteLabels(x) ((x)->DTblFNoteLabels)
#define MifDocumentSetDTblFNoteLabels(x, value) ((x)->DTblFNoteLabels=(value))
#define MifDocumentGetDTblFNoteNumStyle(x) ((x)->DTblFNoteNumStyle)
#define MifDocumentSetDTblFNoteNumStyle(x, value) ((x)->DTblFNoteNumStyle=(value))
#define MifDocumentGetDTblFNoteAnchorPos(x) ((x)->DTblFNoteAnchorPos)
#define MifDocumentSetDTblFNoteAnchorPos(x, value) ((x)->DTblFNoteAnchorPos=(value))
#define MifDocumentGetDTblFNoteNumberPos(x) ((x)->DTblFNoteNumberPos)
#define MifDocumentSetDTblFNoteNumberPos(x, value) ((x)->DTblFNoteNumberPos=(value))
#define MifDocumentGetDTblFNoteAnchorPrefix(x) ((x)->DTblFNoteAnchorPrefix)
#define MifDocumentSetDTblFNoteAnchorPrefix(x, value) ((x)->DTblFNoteAnchorPrefix=(value))
#define MifDocumentGetDTblFNoteAnchorSuffix(x) ((x)->DTblFNoteAnchorSuffix)
#define MifDocumentSetDTblFNoteAnchorSuffix(x, value) ((x)->DTblFNoteAnchorSuffix=(value))
#define MifDocumentGetDTblFNoteNumberPrefix(x) ((x)->DTblFNoteNumberPrefix)
#define MifDocumentSetDTblFNoteNumberPrefix(x, value) ((x)->DTblFNoteNumberPrefix=(value))
#define MifDocumentGetDTblFNoteNumberSuffix(x) ((x)->DTblFNoteNumberSuffix)
#define MifDocumentSetDTblFNoteNumberSuffix(x, value) ((x)->DTblFNoteNumberSuffix=(value))
#define MifDocumentGetDChBarGap(x) ((x)->DChBarGap)
#define MifDocumentSetDChBarGap(x, value) ((x)->DChBarGap=(value))
#define MifDocumentGetDChBarWidth(x) ((x)->DChBarWidth)
#define MifDocumentSetDChBarWidth(x, value) ((x)->DChBarWidth=(value))
#define MifDocumentGetDChBarPosition(x) ((x)->DChBarPosition)
#define MifDocumentSetDChBarPosition(x, value) ((x)->DChBarPosition=(value))
#define MifDocumentGetDAutoChBars(x) ((x)->DAutoChBars)
#define MifDocumentSetDAutoChBars(x, value) ((x)->DAutoChBars=(value))
#define MifDocumentGetDGridOn(x) ((x)->DGridOn)
#define MifDocumentSetDGridOn(x, value) ((x)->DGridOn=(value))
#define MifDocumentGetDRulersOn(x) ((x)->DRulersOn)
#define MifDocumentSetDRulersOn(x, value) ((x)->DRulersOn=(value))
#define MifDocumentGetDBordersOn(x) ((x)->DBordersOn)
#define MifDocumentSetDBordersOn(x, value) ((x)->DBordersOn=(value))
#define MifDocumentGetDSymbolsOn(x) ((x)->DSymbolsOn)
#define MifDocumentSetDSymbolsOn(x, value) ((x)->DSymbolsOn=(value))
#define MifDocumentGetDViewOnly(x) ((x)->DViewOnly)
#define MifDocumentSetDViewOnly(x, value) ((x)->DViewOnly=(value))
#define MifDocumentGetDGraphicsOff(x) ((x)->DGraphicsOff)
#define MifDocumentSetDGraphicsOff(x, value) ((x)->DGraphicsOff=(value))
#define MifDocumentGetDLanguage(x) ((x)->DLanguage)
#define MifDocumentSetDLanguage(x, value) ((x)->DLanguage=(value))
#define MifDocumentGetDMathItalicFunctionName(x) ((x)->DMathItalicFunctionName)
#define MifDocumentSetDMathItalicFunctionName(x, value) ((x)->DMathItalicFunctionName=(value))
#define MifDocumentGetDMathItalicOtherText(x) ((x)->DMathItalicOtherText)
#define MifDocumentSetDMathItalicOtherText(x, value) ((x)->DMathItalicOtherText=(value))
#define MifDocumentGetDMathAlphaCharFontFamily(x) ((x)->DMathAlphaCharFontFamily)
#define MifDocumentSetDMathAlphaCharFontFamily(x, value) ((x)->DMathAlphaCharFontFamily=(value))
#define MifDocumentGetDMathSmallIntegral(x) ((x)->DMathSmallIntegral)
#define MifDocumentSetDMathSmallIntegral(x, value) ((x)->DMathSmallIntegral=(value))
#define MifDocumentGetDMathMediumIntegral(x) ((x)->DMathMediumIntegral)
#define MifDocumentSetDMathMediumIntegral(x, value) ((x)->DMathMediumIntegral=(value))
#define MifDocumentGetDMathLargeIntegral(x) ((x)->DMathLargeIntegral)
#define MifDocumentSetDMathLargeIntegral(x, value) ((x)->DMathLargeIntegral=(value))
#define MifDocumentGetDMathSmallSigma(x) ((x)->DMathSmallSigma)
#define MifDocumentSetDMathSmallSigma(x, value) ((x)->DMathSmallSigma=(value))
#define MifDocumentGetDMathMediumSigma(x) ((x)->DMathMediumSigma)
#define MifDocumentSetDMathMediumSigma(x, value) ((x)->DMathMediumSigma=(value))
#define MifDocumentGetDMathLargeSigma(x) ((x)->DMathLargeSigma)
#define MifDocumentSetDMathLargeSigma(x, value) ((x)->DMathLargeSigma=(value))
#define MifDocumentGetDMathSmallLevel1(x) ((x)->DMathSmallLevel1)
#define MifDocumentSetDMathSmallLevel1(x, value) ((x)->DMathSmallLevel1=(value))
#define MifDocumentGetDMathMediumLevel1(x) ((x)->DMathMediumLevel1)
#define MifDocumentSetDMathMediumLevel1(x, value) ((x)->DMathMediumLevel1=(value))
#define MifDocumentGetDMathLargeLevel1(x) ((x)->DMathLargeLevel1)
#define MifDocumentSetDMathLargeLevel1(x, value) ((x)->DMathLargeLevel1=(value))
#define MifDocumentGetDMathSmallLevel2(x) ((x)->DMathSmallLevel2)
#define MifDocumentSetDMathSmallLevel2(x, value) ((x)->DMathSmallLevel2=(value))
#define MifDocumentGetDMathMediumLevel2(x) ((x)->DMathMediumLevel2)
#define MifDocumentSetDMathMediumLevel2(x, value) ((x)->DMathMediumLevel2=(value))
#define MifDocumentGetDMathLargeLevel2(x) ((x)->DMathLargeLevel2)
#define MifDocumentSetDMathLargeLevel2(x, value) ((x)->DMathLargeLevel2=(value))
#define MifDocumentGetDMathSmallLevel3(x) ((x)->DMathSmallLevel3)
#define MifDocumentSetDMathSmallLevel3(x, value) ((x)->DMathSmallLevel3=(value))
#define MifDocumentGetDMathMediumLevel3(x) ((x)->DMathMediumLevel3)
#define MifDocumentSetDMathMediumLevel3(x, value) ((x)->DMathMediumLevel3=(value))
#define MifDocumentGetDMathLargeLevel3(x) ((x)->DMathLargeLevel3)
#define MifDocumentSetDMathLargeLevel3(x, value) ((x)->DMathLargeLevel3=(value))

/*  BookComponent macros 		*/
#define MifBookComponentGetFileName(x) ((x)->FileName)
#define MifBookComponentSetFileName(x, value) ((x)->FileName=(value))
#define MifBookComponentGetFileNameSuffix(x) ((x)->FileNameSuffix)
#define MifBookComponentSetFileNameSuffix(x, value) ((x)->FileNameSuffix=(value))
#define MifBookComponentGetDeriveType(x) ((x)->DeriveType)
#define MifBookComponentSetDeriveType(x, value) ((x)->DeriveType=(value))
#define MifBookComponentGetDeriveTag(x) ((x)->DeriveTag)
#define MifBookComponentSetDeriveTag(x, value) ((x)->DeriveTag=(value))

/*  Para macros 		*/
#define MifParaGetPgfTag(x) ((x)->PgfTag)
#define MifParaSetPgfTag(x, value) ((x)->PgfTag=(value))
#define MifParaGetPgf(x) ((x)->Pgf)
#define MifParaSetPgf(x, value) ((x)->Pgf=(value))
#define MifParaGetPgfNumString(x) ((x)->PgfNumString)
#define MifParaSetPgfNumString(x, value) ((x)->PgfNumString=(value))
#define MifParaGetPgfEndCond(x) ((x)->PgfEndCond)
#define MifParaSetPgfEndCond(x, value) ((x)->PgfEndCond=(value))
#define MifParaGetPgfCondFullPgf(x) ((x)->PgfCondFullPgf)
#define MifParaSetPgfCondFullPgf(x, value) ((x)->PgfCondFullPgf=(value))
#define MifParaGetParaLine(x) ((x)->ParaLine)
#define MifParaSetParaLine(x, value) ((x)->ParaLine=(value))
#define MifParaGetUnits(x) ((x)->Units)
#define MifParaSetUnits(x, value) ((x)->Units=(value))
#define MifParaGetVerbose(x) ((x)->Verbose)
#define MifParaSetVerbose(x, value) ((x)->Verbose=(value))

/*  FNote macros 		*/
#define MifFNoteGetID(x) ((x)->ID)
#define MifFNoteSetID(x, value) ((x)->ID=(value))
#define MifFNoteGetPara(x) ((x)->Para)
#define MifFNoteSetPara(x, value) ((x)->Para=(value))

/*  Notes macros 		*/
#define MifNotesGetFNote(x) ((x)->FNote)
#define MifNotesSetFNote(x, value) ((x)->FNote=(value))

/*  TextFlow macros 		*/
#define MifTextFlowGetTFTag(x) ((x)->TFTag)
#define MifTextFlowSetTFTag(x, value) ((x)->TFTag=(value))
#define MifTextFlowGetTFAutoConnect(x) ((x)->TFAutoConnect)
#define MifTextFlowSetTFAutoConnect(x, value) ((x)->TFAutoConnect=(value))
#define MifTextFlowGetTFPostScript(x) ((x)->TFPostScript)
#define MifTextFlowSetTFPostScript(x, value) ((x)->TFPostScript=(value))
#define MifTextFlowGetTFFeather(x) ((x)->TFFeather)
#define MifTextFlowSetTFFeather(x, value) ((x)->TFFeather=(value))
#define MifTextFlowGetTFSynchronized(x) ((x)->TFSynchronized)
#define MifTextFlowSetTFSynchronized(x, value) ((x)->TFSynchronized=(value))
#define MifTextFlowGetTFLineSpacing(x) ((x)->TFLineSpacing)
#define MifTextFlowSetTFLineSpacing(x, value) ((x)->TFLineSpacing=(value))
#define MifTextFlowGetTFMinHangHeight(x) ((x)->TFMinHangHeight)
#define MifTextFlowSetTFMinHangHeight(x, value) ((x)->TFMinHangHeight=(value))
#define MifTextFlowGetNotes(x) ((x)->Notes)
#define MifTextFlowSetNotes(x, value) ((x)->Notes=(value))
#define MifTextFlowGetPara(x) ((x)->Para)
#define MifTextFlowSetPara(x, value) ((x)->Para=(value))
#define MifTextFlowGetUnits(x) ((x)->Units)
#define MifTextFlowSetUnits(x, value) ((x)->Units=(value))
#define MifTextFlowGetVerbose(x) ((x)->Verbose)
#define MifTextFlowSetVerbose(x, value) ((x)->Verbose=(value))

/*  CellContent macros 		*/
#define MifCellContentGetNotes(x) ((x)->Notes)
#define MifCellContentSetNotes(x, value) ((x)->Notes=(value))
#define MifCellContentGetPara(x) ((x)->Para)
#define MifCellContentSetPara(x, value) ((x)->Para=(value))

/*  Cell macros 		*/
#define MifCellGetCellFill(x) ((x)->CellFill)
#define MifCellSetCellFill(x, value) ((x)->CellFill=(value))
#define MifCellGetCellSeparation(x) ((x)->CellSeparation)
#define MifCellSetCellSeparation(x, value) ((x)->CellSeparation=(value))
#define MifCellGetCellLRuling(x) ((x)->CellLRuling)
#define MifCellSetCellLRuling(x, value) ((x)->CellLRuling=(value))
#define MifCellGetCellBRuling(x) ((x)->CellBRuling)
#define MifCellSetCellBRuling(x, value) ((x)->CellBRuling=(value))
#define MifCellGetCellRRuling(x) ((x)->CellRRuling)
#define MifCellSetCellRRuling(x, value) ((x)->CellRRuling=(value))
#define MifCellGetCellTRuling(x) ((x)->CellTRuling)
#define MifCellSetCellTRuling(x, value) ((x)->CellTRuling=(value))
#define MifCellGetCellColumns(x) ((x)->CellColumns)
#define MifCellSetCellColumns(x, value) ((x)->CellColumns=(value))
#define MifCellGetCellRows(x) ((x)->CellRows)
#define MifCellSetCellRows(x, value) ((x)->CellRows=(value))
#define MifCellGetCellAffectsColumnWidthA(x) ((x)->CellAffectsColumnWidthA)
#define MifCellSetCellAffectsColumnWidthA(x, value) ((x)->CellAffectsColumnWidthA=(value))
#define MifCellGetCellAngle(x) ((x)->CellAngle)
#define MifCellSetCellAngle(x, value) ((x)->CellAngle=(value))
#define MifCellGetCellContent(x) ((x)->CellContent)
#define MifCellSetCellContent(x, value) ((x)->CellContent=(value))

/*  Row macros 		*/
#define MifRowGetConditional(x) ((x)->Conditional)
#define MifRowSetConditional(x, value) ((x)->Conditional=(value))
#define MifRowGetRowWithNext(x) ((x)->RowWithNext)
#define MifRowSetRowWithNext(x, value) ((x)->RowWithNext=(value))
#define MifRowGetRowWithPrev(x) ((x)->RowWithPrev)
#define MifRowSetRowWithPrev(x, value) ((x)->RowWithPrev=(value))
#define MifRowGetRowMinHeight(x) ((x)->RowMinHeight)
#define MifRowSetRowMinHeight(x, value) ((x)->RowMinHeight=(value))
#define MifRowGetRowMaxHeight(x) ((x)->RowMaxHeight)
#define MifRowSetRowMaxHeight(x, value) ((x)->RowMaxHeight=(value))
#define MifRowGetRowHeight(x) ((x)->RowHeight)
#define MifRowSetRowHeight(x, value) ((x)->RowHeight=(value))
#define MifRowGetRowPlacement(x) ((x)->RowPlacement)
#define MifRowSetRowPlacement(x, value) ((x)->RowPlacement=(value))
#define MifRowGetCell(x) ((x)->Cell)
#define MifRowSetCell(x, value) ((x)->Cell=(value))

/*  TblH macros 		*/
#define MifTblHGetRow(x) ((x)->Row)
#define MifTblHSetRow(x, value) ((x)->Row=(value))

/*  TblBody macros 		*/
#define MifTblBodyGetRow(x) ((x)->Row)
#define MifTblBodySetRow(x, value) ((x)->Row=(value))

/*  TblF macros 		*/
#define MifTblFGetRow(x) ((x)->Row)
#define MifTblFSetRow(x, value) ((x)->Row=(value))

/*  TblTitleContent macros 		*/
#define MifTblTitleContentGetNotes(x) ((x)->Notes)
#define MifTblTitleContentSetNotes(x, value) ((x)->Notes=(value))
#define MifTblTitleContentGetPara(x) ((x)->Para)
#define MifTblTitleContentSetPara(x, value) ((x)->Para=(value))

/*  Tbl macros 		*/
#define MifTblGetTblID(x) ((x)->TblID)
#define MifTblSetTblID(x, value) ((x)->TblID=(value))
#define MifTblGetTblTag(x) ((x)->TblTag)
#define MifTblSetTblTag(x, value) ((x)->TblTag=(value))
#define MifTblGetTblFormat(x) ((x)->TblFormat)
#define MifTblSetTblFormat(x, value) ((x)->TblFormat=(value))
#define MifTblGetTblNumColumns(x) ((x)->TblNumColumns)
#define MifTblSetTblNumColumns(x, value) ((x)->TblNumColumns=(value))
#define MifTblGetTblColumnWidth(x) ((x)->TblColumnWidth)
#define MifTblSetTblColumnWidth(x, value) ((x)->TblColumnWidth=(value))
#define MifTblGetTblTitleContent(x) ((x)->TblTitleContent)
#define MifTblSetTblTitleContent(x, value) ((x)->TblTitleContent=(value))
#define MifTblGetTblH(x) ((x)->TblH)
#define MifTblSetTblH(x, value) ((x)->TblH=(value))
#define MifTblGetTblBody(x) ((x)->TblBody)
#define MifTblSetTblBody(x, value) ((x)->TblBody=(value))
#define MifTblGetTblF(x) ((x)->TblF)
#define MifTblSetTblF(x, value) ((x)->TblF=(value))
#define MifTblColumnWidthListGetNext(x) ((x)->Next)
#define MifTblColumnWidthListSetNext(x, value) ((x)->Next=(value))
#define MifTblColumnWidthListGetPrev(x) ((x)->Prev)
#define MifTblColumnWidthListSetPrev(x, value) ((x)->Prev=(value))
#define MifTblColumnWidthListGetTblColumnWidth(x) ((x)->TblColumnWidth)
#define MifTblColumnWidthListSetTblColumnWidth(x, value) ((x)->TblColumnWidth=(value))

/*  Tbls macros 		*/
#define MifTblsGetTbl(x) ((x)->Tbl)
#define MifTblsSetTbl(x, value) ((x)->Tbl=(value))

/*  ArrowStyle macros 		*/
#define MifArrowStyleGetTipAngle(x) ((x)->TipAngle)
#define MifArrowStyleSetTipAngle(x, value) ((x)->TipAngle=(value))
#define MifArrowStyleGetBaseAngle(x) ((x)->BaseAngle)
#define MifArrowStyleSetBaseAngle(x, value) ((x)->BaseAngle=(value))
#define MifArrowStyleGetLength(x) ((x)->Length)
#define MifArrowStyleSetLength(x, value) ((x)->Length=(value))
#define MifArrowStyleGetHeadType(x) ((x)->HeadType)
#define MifArrowStyleSetHeadType(x, value) ((x)->HeadType=(value))
#define MifArrowStyleGetScaleHead(x) ((x)->ScaleHead)
#define MifArrowStyleSetScaleHead(x, value) ((x)->ScaleHead=(value))
#define MifArrowStyleGetScaleFactor(x) ((x)->ScaleFactor)
#define MifArrowStyleSetScaleFactor(x, value) ((x)->ScaleFactor=(value))

/*  GenericObject macros 		*/
#define MifGenericObjectGetID(x) ((x)->ID)
#define MifGenericObjectSetID(x, value) ((x)->ID=(value))
#define MifGenericObjectGetGroupID(x) ((x)->GroupID)
#define MifGenericObjectSetGroupID(x, value) ((x)->GroupID=(value))
#define MifGenericObjectGetPen(x) ((x)->Pen)
#define MifGenericObjectSetPen(x, value) ((x)->Pen=(value))
#define MifGenericObjectGetFill(x) ((x)->Fill)
#define MifGenericObjectSetFill(x, value) ((x)->Fill=(value))
#define MifGenericObjectGetPenWidth(x) ((x)->PenWidth)
#define MifGenericObjectSetPenWidth(x, value) ((x)->PenWidth=(value))
#define MifGenericObjectGetSeparation(x) ((x)->Separation)
#define MifGenericObjectSetSeparation(x, value) ((x)->Separation=(value))
#define MifGenericObjectGetUnits(x) ((x)->Units)
#define MifGenericObjectSetUnits(x, value) ((x)->Units=(value))
#define MifGenericObjectGetVerbose(x) ((x)->Verbose)
#define MifGenericObjectSetVerbose(x, value) ((x)->Verbose=(value))
#define MifGenericObjectGetObAngle(x) ((x)->ObAngle)
#define MifGenericObjectSetObAngle(x, value) ((x)->ObAngle=(value))
#define MifGenericObjectGetReRotateAngle(x) ((x)->ReRotateAngle)
#define MifGenericObjectSetReRotateAngle(x, value) ((x)->ReRotateAngle=(value))
#define MifGenericObjectGetObColor(x) ((x)->ObColor)
#define MifGenericObjectSetObColor(x, value) ((x)->ObColor=(value))
#define MifGenericObjectGetOverprint(x) ((x)->Overprint)
#define MifGenericObjectSetOverprint(x, value) ((x)->Overprint=(value))

/*  Arc macros 		*/
#define MifArcGetGenericObject(x) ((x)->GenericObject)
#define MifArcSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifArcGetHeadCap(x) ((x)->HeadCap)
#define MifArcSetHeadCap(x, value) ((x)->HeadCap=(value))
#define MifArcGetTailCap(x) ((x)->TailCap)
#define MifArcSetTailCap(x, value) ((x)->TailCap=(value))
#define MifArcGetArrowStyle(x) ((x)->ArrowStyle)
#define MifArcSetArrowStyle(x, value) ((x)->ArrowStyle=(value))
#define MifArcGetArcRect(x) ((x)->ArcRect)
#define MifArcSetArcRect(x, value) ((x)->ArcRect=(value))
#define MifArcGetArcTheta(x) ((x)->ArcTheta)
#define MifArcSetArcTheta(x, value) ((x)->ArcTheta=(value))
#define MifArcGetArcDTheta(x) ((x)->ArcDTheta)
#define MifArcSetArcDTheta(x, value) ((x)->ArcDTheta=(value))

/*  Ellipse macros 		*/
#define MifEllipseGetGenericObject(x) ((x)->GenericObject)
#define MifEllipseSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifEllipseGetBRect(x) ((x)->BRect)
#define MifEllipseSetBRect(x, value) ((x)->BRect=(value))

/*  Polygon macros 		*/
#define MifPolygonGetGenericObject(x) ((x)->GenericObject)
#define MifPolygonSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifPolygonGetSmoothed(x) ((x)->Smoothed)
#define MifPolygonSetSmoothed(x, value) ((x)->Smoothed=(value))
#define MifPolygonGetNumPoints(x) ((x)->NumPoints)
#define MifPolygonSetNumPoints(x, value) ((x)->NumPoints=(value))
#define MifPolygonGetPoint(x) ((x)->Point)
#define MifPolygonSetPoint(x, value) ((x)->Point=(value))
#define MifPointListGetNext(x) ((x)->Next)
#define MifPointListSetNext(x, value) ((x)->Next=(value))
#define MifPointListGetPrev(x) ((x)->Prev)
#define MifPointListSetPrev(x, value) ((x)->Prev=(value))
#define MifPointListGetPoint(x) ((x)->Point)
#define MifPointListSetPoint(x, value) ((x)->Point=(value))

/*  PolyLine macros 		*/
#define MifPolyLineGetGenericObject(x) ((x)->GenericObject)
#define MifPolyLineSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifPolyLineGetHeadCap(x) ((x)->HeadCap)
#define MifPolyLineSetHeadCap(x, value) ((x)->HeadCap=(value))
#define MifPolyLineGetTailCap(x) ((x)->TailCap)
#define MifPolyLineSetTailCap(x, value) ((x)->TailCap=(value))
#define MifPolyLineGetArrowStyle(x) ((x)->ArrowStyle)
#define MifPolyLineSetArrowStyle(x, value) ((x)->ArrowStyle=(value))
#define MifPolyLineGetSmoothed(x) ((x)->Smoothed)
#define MifPolyLineSetSmoothed(x, value) ((x)->Smoothed=(value))
#define MifPolyLineGetNumPoints(x) ((x)->NumPoints)
#define MifPolyLineSetNumPoints(x, value) ((x)->NumPoints=(value))
#define MifPolyLineGetPoint(x) ((x)->Point)
#define MifPolyLineSetPoint(x, value) ((x)->Point=(value))

/*  Rectangle macros 		*/
#define MifRectangleGetGenericObject(x) ((x)->GenericObject)
#define MifRectangleSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifRectangleGetBRect(x) ((x)->BRect)
#define MifRectangleSetBRect(x, value) ((x)->BRect=(value))
#define MifRectangleGetSmoothed(x) ((x)->Smoothed)
#define MifRectangleSetSmoothed(x, value) ((x)->Smoothed=(value))

/*  TextLine macros 		*/
#define MifTextLineGetGenericObject(x) ((x)->GenericObject)
#define MifTextLineSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifTextLineGetTLOrigin(x) ((x)->TLOrigin)
#define MifTextLineSetTLOrigin(x, value) ((x)->TLOrigin=(value))
#define MifTextLineGetTLAlignment(x) ((x)->TLAlignment)
#define MifTextLineSetTLAlignment(x, value) ((x)->TLAlignment=(value))
#define MifTextLineGetAngle(x) ((x)->Angle)
#define MifTextLineSetAngle(x, value) ((x)->Angle=(value))
#define MifTextLineGetLineItems(x) ((x)->LineItems)
#define MifTextLineSetLineItems(x, value) ((x)->LineItems=(value))
#define MifTextLineGetFont(x) ((x)->Font)
#define MifTextLineSetFont(x, value) ((x)->Font=(value))
#define MifTextLineGetString(x) ((x)->String)
#define MifTextLineSetString(x, value) ((x)->String=(value))
#define MifTextLineGetChar(x) ((x)->Char)
#define MifTextLineSetChar(x, value) ((x)->Char=(value))

/*  TextRect macros 		*/
#define MifTextRectGetGenericObject(x) ((x)->GenericObject)
#define MifTextRectSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifTextRectGetAngle(x) ((x)->Angle)
#define MifTextRectSetAngle(x, value) ((x)->Angle=(value))
#define MifTextRectGetBRect(x) ((x)->BRect)
#define MifTextRectSetBRect(x, value) ((x)->BRect=(value))
#define MifTextRectGetTRNext(x) ((x)->TRNext)
#define MifTextRectSetTRNext(x, value) ((x)->TRNext=(value))

/*  RoundRect macros 		*/
#define MifRoundRectGetGenericObject(x) ((x)->GenericObject)
#define MifRoundRectSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifRoundRectGetBRect(x) ((x)->BRect)
#define MifRoundRectSetBRect(x, value) ((x)->BRect=(value))
#define MifRoundRectGetRadius(x) ((x)->Radius)
#define MifRoundRectSetRadius(x, value) ((x)->Radius=(value))

/*  Math macros 		*/
#define MifMathGetGroupID(x) ((x)->GroupID)
#define MifMathSetGroupID(x, value) ((x)->GroupID=(value))
#define MifMathGetSeparation(x) ((x)->Separation)
#define MifMathSetSeparation(x, value) ((x)->Separation=(value))
#define MifMathGetBRect(x) ((x)->BRect)
#define MifMathSetBRect(x, value) ((x)->BRect=(value))
#define MifMathGetMathFullForm(x) ((x)->MathFullForm)
#define MifMathSetMathFullForm(x, value) ((x)->MathFullForm=(value))
#define MifMathGetMathOrigin(x) ((x)->MathOrigin)
#define MifMathSetMathOrigin(x, value) ((x)->MathOrigin=(value))
#define MifMathGetMathAlignment(x) ((x)->MathAlignment)
#define MifMathSetMathAlignment(x, value) ((x)->MathAlignment=(value))
#define MifMathGetMathSize(x) ((x)->MathSize)
#define MifMathSetMathSize(x, value) ((x)->MathSize=(value))
#define MifMathGetAngle(x) ((x)->Angle)
#define MifMathSetAngle(x, value) ((x)->Angle=(value))

/*  Group macros 		*/
#define MifGroupGetGroupID(x) ((x)->GroupID)
#define MifGroupSetGroupID(x, value) ((x)->GroupID=(value))
#define MifGroupGetID(x) ((x)->ID)
#define MifGroupSetID(x, value) ((x)->ID=(value))
#define MifGroupGetAngle(x) ((x)->Angle)
#define MifGroupSetAngle(x, value) ((x)->Angle=(value))

/*  ImportObject macros 		*/
#define MifImportObjectGetGenericObject(x) ((x)->GenericObject)
#define MifImportObjectSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifImportObjectGetImportObFile(x) ((x)->ImportObFile)
#define MifImportObjectSetImportObFile(x, value) ((x)->ImportObFile=(value))
#define MifImportObjectGetImportObFileDI(x) ((x)->ImportObFileDI)
#define MifImportObjectSetImportObFileDI(x, value) ((x)->ImportObFileDI=(value))
#define MifImportObjectGetBRect(x) ((x)->BRect)
#define MifImportObjectSetBRect(x, value) ((x)->BRect=(value))
#define MifImportObjectGetBitMapDpi(x) ((x)->BitMapDpi)
#define MifImportObjectSetBitMapDpi(x, value) ((x)->BitMapDpi=(value))
#define MifImportObjectGetAngle(x) ((x)->Angle)
#define MifImportObjectSetAngle(x, value) ((x)->Angle=(value))
#define MifImportObjectGetFlipLR(x) ((x)->FlipLR)
#define MifImportObjectSetFlipLR(x, value) ((x)->FlipLR=(value))
#define MifImportObjectGetFacet(x) ((x)->Facet)
#define MifImportObjectSetFacet(x, value) ((x)->Facet=(value))
#define MifImportObjectGetImportObEditor(x) ((x)->ImportObEditor)
#define MifImportObjectSetImportObEditor(x, value) ((x)->ImportObEditor=(value))
#define MifImportObjectGetImportObUpdator(x) ((x)->ImportObUpdator)
#define MifImportObjectSetImportObUpdator(x, value) ((x)->ImportObUpdator=(value))

/*  Frame macros 		*/
#define MifFrameGetGenericObject(x) ((x)->GenericObject)
#define MifFrameSetGenericObject(x, value) ((x)->GenericObject=(value))
#define MifFrameGetBRect(x) ((x)->BRect)
#define MifFrameSetBRect(x, value) ((x)->BRect=(value))
#define MifFrameGetFrameType(x) ((x)->FrameType)
#define MifFrameSetFrameType(x, value) ((x)->FrameType=(value))
#define MifFrameGetTag(x) ((x)->Tag)
#define MifFrameSetTag(x, value) ((x)->Tag=(value))
#define MifFrameGetFloat(x) ((x)->Float)
#define MifFrameSetFloat(x, value) ((x)->Float=(value))
#define MifFrameGetNSOffset(x) ((x)->NSOffset)
#define MifFrameSetNSOffset(x, value) ((x)->NSOffset=(value))
#define MifFrameGetBLOffset(x) ((x)->BLOffset)
#define MifFrameSetBLOffset(x, value) ((x)->BLOffset=(value))
#define MifFrameGetAnchorAlign(x) ((x)->AnchorAlign)
#define MifFrameSetAnchorAlign(x, value) ((x)->AnchorAlign=(value))
#define MifFrameGetCropped(x) ((x)->Cropped)
#define MifFrameSetCropped(x, value) ((x)->Cropped=(value))
#define MifFrameGetObjects(x) ((x)->Objects)
#define MifFrameSetObjects(x, value) ((x)->Objects=(value))
#define MifFrameGetFrame(x) ((x)->Frame)
#define MifFrameSetFrame(x, value) ((x)->Frame=(value))
#define MifFrameGetArc(x) ((x)->Arc)
#define MifFrameSetArc(x, value) ((x)->Arc=(value))
#define MifFrameGetEllipse(x) ((x)->Ellipse)
#define MifFrameSetEllipse(x, value) ((x)->Ellipse=(value))
#define MifFrameGetGroup(x) ((x)->Group)
#define MifFrameSetGroup(x, value) ((x)->Group=(value))
#define MifFrameGetImportObject(x) ((x)->ImportObject)
#define MifFrameSetImportObject(x, value) ((x)->ImportObject=(value))
#define MifFrameGetMath(x) ((x)->Math)
#define MifFrameSetMath(x, value) ((x)->Math=(value))
#define MifFrameGetPolygon(x) ((x)->Polygon)
#define MifFrameSetPolygon(x, value) ((x)->Polygon=(value))
#define MifFrameGetPolyLine(x) ((x)->PolyLine)
#define MifFrameSetPolyLine(x, value) ((x)->PolyLine=(value))
#define MifFrameGetRectangle(x) ((x)->Rectangle)
#define MifFrameSetRectangle(x, value) ((x)->Rectangle=(value))
#define MifFrameGetRoundRect(x) ((x)->RoundRect)
#define MifFrameSetRoundRect(x, value) ((x)->RoundRect=(value))
#define MifFrameGetTextLine(x) ((x)->TextLine)
#define MifFrameSetTextLine(x, value) ((x)->TextLine=(value))
#define MifFrameGetTextRect(x) ((x)->TextRect)
#define MifFrameSetTextRect(x, value) ((x)->TextRect=(value))

/*  Page macros 		*/
#define MifPageGetPageType(x) ((x)->PageType)
#define MifPageSetPageType(x, value) ((x)->PageType=(value))
#define MifPageGetPageNum(x) ((x)->PageNum)
#define MifPageSetPageNum(x, value) ((x)->PageNum=(value))
#define MifPageGetPageTag(x) ((x)->PageTag)
#define MifPageSetPageTag(x, value) ((x)->PageTag=(value))
#define MifPageGetPageSize(x) ((x)->PageSize)
#define MifPageSetPageSize(x, value) ((x)->PageSize=(value))
#define MifPageGetPageOrientation(x) ((x)->PageOrientation)
#define MifPageSetPageOrientation(x, value) ((x)->PageOrientation=(value))
#define MifPageGetPageBackground(x) ((x)->PageBackground)
#define MifPageSetPageBackground(x, value) ((x)->PageBackground=(value))
#define MifPageGetUnits(x) ((x)->Units)
#define MifPageSetUnits(x, value) ((x)->Units=(value))
#define MifPageGetVerbose(x) ((x)->Verbose)
#define MifPageSetVerbose(x, value) ((x)->Verbose=(value))
#define MifPageGetObjects(x) ((x)->Objects)
#define MifPageSetObjects(x, value) ((x)->Objects=(value))
#define MifPageGetFrame(x) ((x)->Frame)
#define MifPageSetFrame(x, value) ((x)->Frame=(value))
#define MifPageGetArc(x) ((x)->Arc)
#define MifPageSetArc(x, value) ((x)->Arc=(value))
#define MifPageGetEllipse(x) ((x)->Ellipse)
#define MifPageSetEllipse(x, value) ((x)->Ellipse=(value))
#define MifPageGetGroup(x) ((x)->Group)
#define MifPageSetGroup(x, value) ((x)->Group=(value))
#define MifPageGetImportObject(x) ((x)->ImportObject)
#define MifPageSetImportObject(x, value) ((x)->ImportObject=(value))
#define MifPageGetMath(x) ((x)->Math)
#define MifPageSetMath(x, value) ((x)->Math=(value))
#define MifPageGetPolygon(x) ((x)->Polygon)
#define MifPageSetPolygon(x, value) ((x)->Polygon=(value))
#define MifPageGetPolyLine(x) ((x)->PolyLine)
#define MifPageSetPolyLine(x, value) ((x)->PolyLine=(value))
#define MifPageGetRectangle(x) ((x)->Rectangle)
#define MifPageSetRectangle(x, value) ((x)->Rectangle=(value))
#define MifPageGetRoundRect(x) ((x)->RoundRect)
#define MifPageSetRoundRect(x, value) ((x)->RoundRect=(value))
#define MifPageGetTextLine(x) ((x)->TextLine)
#define MifPageSetTextLine(x, value) ((x)->TextLine=(value))
#define MifPageGetTextRect(x) ((x)->TextRect)
#define MifPageSetTextRect(x, value) ((x)->TextRect=(value))

/*  Dictionary macros 		*/
#define MifDictionaryGetOKWord(x) ((x)->OKWord)
#define MifDictionarySetOKWord(x, value) ((x)->OKWord=(value))
#define MifOKWordListGetNext(x) ((x)->Next)
#define MifOKWordListSetNext(x, value) ((x)->Next=(value))
#define MifOKWordListGetPrev(x) ((x)->Prev)
#define MifOKWordListSetPrev(x, value) ((x)->Prev=(value))
#define MifOKWordListGetOKWord(x) ((x)->OKWord)
#define MifOKWordListSetOKWord(x, value) ((x)->OKWord=(value))

/*  AFrames macros 		*/
#define MifAFramesGetFrame(x) ((x)->Frame)
#define MifAFramesSetFrame(x, value) ((x)->Frame=(value))

/*  MIFTop macros 		*/
#define MifMIFTopGetMIFFile(x) ((x)->MIFFile)
#define MifMIFTopSetMIFFile(x, value) ((x)->MIFFile=(value))
#define MifMIFTopGetVerbose(x) ((x)->Verbose)
#define MifMIFTopSetVerbose(x, value) ((x)->Verbose=(value))
#define MifMIFTopGetUnits(x) ((x)->Units)
#define MifMIFTopSetUnits(x, value) ((x)->Units=(value))
#define MifMIFTopGetComment(x) ((x)->Comment)
#define MifMIFTopSetComment(x, value) ((x)->Comment=(value))
#define MifMIFTopGetConditionCatalog(x) ((x)->ConditionCatalog)
#define MifMIFTopSetConditionCatalog(x, value) ((x)->ConditionCatalog=(value))
#define MifMIFTopGetPgfCatalog(x) ((x)->PgfCatalog)
#define MifMIFTopSetPgfCatalog(x, value) ((x)->PgfCatalog=(value))
#define MifMIFTopGetFontCatalog(x) ((x)->FontCatalog)
#define MifMIFTopSetFontCatalog(x, value) ((x)->FontCatalog=(value))
#define MifMIFTopGetRulingCatalog(x) ((x)->RulingCatalog)
#define MifMIFTopSetRulingCatalog(x, value) ((x)->RulingCatalog=(value))
#define MifMIFTopGetTblCatalog(x) ((x)->TblCatalog)
#define MifMIFTopSetTblCatalog(x, value) ((x)->TblCatalog=(value))
#define MifMIFTopGetVariableFormats(x) ((x)->VariableFormats)
#define MifMIFTopSetVariableFormats(x, value) ((x)->VariableFormats=(value))
#define MifMIFTopGetXRefFormats(x) ((x)->XRefFormats)
#define MifMIFTopSetXRefFormats(x, value) ((x)->XRefFormats=(value))
#define MifMIFTopGetBookComponent(x) ((x)->BookComponent)
#define MifMIFTopSetBookComponent(x, value) ((x)->BookComponent=(value))
#define MifMIFTopGetDictionary(x) ((x)->Dictionary)
#define MifMIFTopSetDictionary(x, value) ((x)->Dictionary=(value))
#define MifMIFTopGetTbls(x) ((x)->Tbls)
#define MifMIFTopSetTbls(x, value) ((x)->Tbls=(value))
#define MifMIFTopGetAFrames(x) ((x)->AFrames)
#define MifMIFTopSetAFrames(x, value) ((x)->AFrames=(value))
#define MifMIFTopGetPage(x) ((x)->Page)
#define MifMIFTopSetPage(x, value) ((x)->Page=(value))
#define MifMIFTopGetTextFlow(x) ((x)->TextFlow)
#define MifMIFTopSetTextFlow(x, value) ((x)->TextFlow=(value))
#define MifMIFTopGetDocument(x) ((x)->Document)
#define MifMIFTopSetDocument(x, value) ((x)->Document=(value))

/*  Color macros 		*/
#define MifColorGetColorTag(x) ((x)->ColorTag)
#define MifColorSetColorTag(x, value) ((x)->ColorTag=(value))
#define MifColorGetColorCyan(x) ((x)->ColorCyan)
#define MifColorSetColorCyan(x, value) ((x)->ColorCyan=(value))
#define MifColorGetColorMagenta(x) ((x)->ColorMagenta)
#define MifColorSetColorMagenta(x, value) ((x)->ColorMagenta=(value))
#define MifColorGetColorYellow(x) ((x)->ColorYellow)
#define MifColorSetColorYellow(x, value) ((x)->ColorYellow=(value))
#define MifColorGetColorBlack(x) ((x)->ColorBlack)
#define MifColorSetColorBlack(x, value) ((x)->ColorBlack=(value))
#define MifColorGetColorPantoneValue(x) ((x)->ColorPantoneValue)
#define MifColorSetColorPantoneValue(x, value) ((x)->ColorPantoneValue=(value))
#define MifColorGetColorAttribute(x) ((x)->ColorAttribute)
#define MifColorSetColorAttribute(x, value) ((x)->ColorAttribute=(value))

/*  ColorCatalog macros 		*/
#define MifColorCatalogGetUnits(x) ((x)->Units)
#define MifColorCatalogSetUnits(x, value) ((x)->Units=(value))
#define MifColorCatalogGetVerbose(x) ((x)->Verbose)
#define MifColorCatalogSetVerbose(x, value) ((x)->Verbose=(value))
#define MifColorCatalogGetColor(x) ((x)->Color)
#define MifColorCatalogSetColor(x, value) ((x)->Color=(value))
