//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 01:08:14 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:xliff:matches:2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.globalsight.everest.edit.offline.xliff.xliff20.match;
