//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 01:08:14 ÏÂÎç CST 
//


package com.globalsight.everest.edit.offline.xliff.xliff20.match;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="am"/>
 *     &lt;enumeration value="mt"/>
 *     &lt;enumeration value="icm"/>
 *     &lt;enumeration value="idm"/>
 *     &lt;enumeration value="tb"/>
 *     &lt;enumeration value="tm"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeValues")
@XmlEnum
public enum TypeValues {

    @XmlEnumValue("am")
    AM("am"),
    @XmlEnumValue("mt")
    MT("mt"),
    @XmlEnumValue("icm")
    ICM("icm"),
    @XmlEnumValue("idm")
    IDM("idm"),
    @XmlEnumValue("tb")
    TB("tb"),
    @XmlEnumValue("tm")
    TM("tm"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    TypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeValues fromValue(String v) {
        for (TypeValues c: TypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
