/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountPanel.java
 *
 * Created on 2010-6-29, 16:38:04
 */

package testUI;
import javax.swing.*;
import javax.swing.event.*;
import util.Account;

import java.util.ArrayList;
import util.*;

/**
 *
 * @author likun
 */
public class AccountPanel extends javax.swing.JPanel {

    /** Creates new form AccountPanel 
    public AccountPanel() {
        initComponents();
    }
     */
    public AccountPanel(ArrayList<Account> accountsList){
        if(accountsList != null){
            for(Account account : accountsList){
                model.addElement(account);
            }
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        listScrollPane = new javax.swing.JScrollPane();
        //model = new DefaultListModel();
        //model.addElement(a1);
        //model.addElement(a2); //model should be initialized when AccountPanel initialization
        accountsList = new javax.swing.JList();
        mainPanel = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        hostTextField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        portTextField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        leftPanel = new javax.swing.JPanel();
        lowerPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        httpsJCheckBox = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        splitPane.setName("splitPane"); // NOI18N

        listScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        listScrollPane.setName("listScrollPane"); // NOI18N

        accountsList.setModel(model);
        accountsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        accountsList.setCellRenderer(new AccountCellRenderer());
        accountsList.setName("accountsList"); // NOI18N
        accountsList.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                Account account = (Account) accountsList.getSelectedValue();
                hostTextField.setText(account.getHost());
                portTextField.setText(account.getPort());
                userNameTextField.setText(account.getUserName());
                passwordTextField.setText(account.getPassword());
                httpsJCheckBox.setSelected(account.getHttps().equals("true")?true:false);
            }
        });
        listScrollPane.setViewportView(accountsList);

        splitPane.setLeftComponent(listScrollPane);

        mainPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.GridLayout(2, 1));

        upperPanel.setName("upperPanel"); // NOI18N
        upperPanel.setLayout(new java.awt.GridLayout());

        rightPanel.setName("rightPanel"); // NOI18N
        upperPanel.add(rightPanel);

        centerPanel.setName("centerPanel"); // NOI18N
        centerPanel.setLayout(new java.awt.GridLayout(4, 2));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(testtool.TestToolApp.class).getContext().getResourceMap(AccountPanel.class);
        hostLabel.setText(resourceMap.getString("hostLabel.text")); // NOI18N
        hostLabel.setName("hostLabel"); // NOI18N
        centerPanel.add(hostLabel);

        hostTextField.setColumns(50);
        hostTextField.setText(resourceMap.getString("hostTextField.text")); // NOI18N
        hostTextField.setName("hostTextField"); // NOI18N
        centerPanel.add(hostTextField);

        portLabel.setText(resourceMap.getString("portLabel.text")); // NOI18N
        portLabel.setName("portLabel"); // NOI18N
        centerPanel.add(portLabel);

        portTextField.setColumns(30);
        portTextField.setText(resourceMap.getString("portTextField.text")); // NOI18N
        portTextField.setName("portTextField"); // NOI18N
        centerPanel.add(portTextField);

        userNameLabel.setText(resourceMap.getString("userNameLabel.text")); // NOI18N
        userNameLabel.setName("userNameLabel"); // NOI18N
        centerPanel.add(userNameLabel);

        userNameTextField.setColumns(30);
        userNameTextField.setText(resourceMap.getString("userNameTextField.text")); // NOI18N
        userNameTextField.setName("userNameTextField"); // NOI18N
        centerPanel.add(userNameTextField);

        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N
        centerPanel.add(passwordLabel);

        passwordTextField.setText(resourceMap.getString("passwordTextField.text")); // NOI18N
        passwordTextField.setName("passwordTextField"); // NOI18N
        centerPanel.add(passwordTextField);

        upperPanel.add(centerPanel);

        leftPanel.setName("leftPanel"); // NOI18N
        upperPanel.add(leftPanel);

        mainPanel.add(upperPanel);

        lowerPanel.setName("lowerPanel"); // NOI18N

        loginButton.setText(resourceMap.getString("loginButton.text")); // NOI18N
        loginButton.setName("loginButton"); // NOI18N
        lowerPanel.add(loginButton);

        mainPanel.add(lowerPanel);

        splitPane.setRightComponent(mainPanel);

        add(splitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList accountsList;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JTextField hostTextField;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JCheckBox httpsJCheckBox;
    // End of variables declaration//GEN-END:variables

    //Account a1 = new Account("192.168.105.209","80","companyliadmin","password");
    //Account a2 = new Account("192.168.105.209","80","companyliuadmin","password");
    public DefaultListModel model = new DefaultListModel();
    public final String NO_ACCOUNT = "No Account Available";



}
