/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Label_TextField_Panel.java
 *
 * Created on 2010-7-2, 15:03:33
 */

package testUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author likun
 */
public class Label_TextField_Panel extends javax.swing.JPanel {

    /** Creates new form Label_TextField_Panel */
    public Label_TextField_Panel() {
        initComponents();
    }

    public void setLabel(String text){
        label.setText(text);
    }
    
    public void setTextField(String text){
        textField.setText(text);
    }
    //For base64Binary type (byte[])
    public void setJButton(){
    	addFileButton.setVisible(true);
    	addFileButton.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
            	JFileChooser fileChooser = new JFileChooser("C:\\");
                fileChooser.setDialogTitle("Select The File");
                fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
                fileChooser.setMultiSelectionEnabled(false);
                int status = fileChooser.showOpenDialog(getParent());
                File selectedFile = fileChooser.getSelectedFile();
                setTextField(selectedFile.getAbsolutePath());
            }
        });
    }

    public JLabel getLabel(){
        return this.label;
    }
    public JTextField getTextField(){
        return this.textField;
    }
    
    public JButton getJButton(){
    	return this.addFileButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        addFileButton = new javax.swing.JButton("Add File");

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(testtool.TestToolApp.class).getContext().getResourceMap(Label_TextField_Panel.class);
        label.setText(resourceMap.getString("label.text")); // NOI18N
        label.setName("label"); // NOI18N
        add(label);

        textField.setText(resourceMap.getString("textField.text")); // NOI18N
        textField.setName("textField"); // NOI18N
        add(textField);  
        
        addFileButton.setVisible(false);
        add(addFileButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JTextField textField;
    private javax.swing.JButton addFileButton;
    // End of variables declaration//GEN-END:variables

}
