/*
 * AboutDlg.java
 *
 * Created on May 10, 2004, 4:16 PM
 */

package galign.ui.view;

import java.awt.Component;
import java.awt.Font;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;

import galign.Setup;

/**
 *
 * @author  cvdlaan
 */
public class AboutDlg extends javax.swing.JDialog
{

    /** Creates new form AboutDlg */
    public AboutDlg (java.awt.Frame parent, boolean modal)
    {
        super (parent, modal);
        initComponents ();
        setTitle(Setup.getString("label.galign"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        JButton jButton1 = new JButton();

        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        String version = galign.BuildVersion.BUILD_VERSION;
        
        JLabel label1 = new JLabel();
        label1.setText(Setup.getString("label.aligner"));
        Font oldFont = label1.getFont();
        Font newFont = oldFont.deriveFont(Font.BOLD);
        label1.setFont(newFont);
        JLabel label2 = new JLabel();
        label2.setText(Setup.getString("label.version") + " " + version);
        JLabel label3 = new JLabel();
        label3.setText(Setup.getString("label.copywrite"));
        //getContentPane().add(lb_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        label1.setAlignmentX(Component.CENTER_ALIGNMENT);
        label2.setAlignmentX(Component.CENTER_ALIGNMENT);
        label3.setAlignmentX(Component.CENTER_ALIGNMENT);
        getContentPane().add(new JLabel(" "));
        getContentPane().add(label1);
        getContentPane().add(new JLabel(" "));
        getContentPane().add(label2);
        getContentPane().add(new JLabel(" "));
        getContentPane().add(label3);
        getContentPane().add(new JLabel(" "));

        jButton1.setText(Setup.getString("btn.ok"));
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                doOnOK(evt);
            }
        });

        //getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        jButton1.setAlignmentX(Component.CENTER_ALIGNMENT);
        getContentPane().add(jButton1);

        pack();
    }//GEN-END:initComponents

    private void doOnOK (java.awt.event.ActionEvent evt)//GEN-FIRST:event_doOnOK
    {//GEN-HEADEREND:event_doOnOK
        dispose();
    }//GEN-LAST:event_doOnOK

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        new AboutDlg (new javax.swing.JFrame (), true).show ();
    }


}
