/*
 * ExportProjectPnl.java
 *
 * Created on May 11, 2004, 1:17 AM
 */

package galign.ui.view;

/**
 *
 * @author  cvdlaan
 */
public class ExportProjectPnl extends javax.swing.JPanel
{
    
    /** Creates new form ExportProjectPnl */
    public ExportProjectPnl ()
    {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("<HTML><B>Export Files To TMX</B></HTML>");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Select Files:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Reviewed Files" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {new Boolean(true), "test_en_US.html", "test_de_DE.html"},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Selected", "Source", "Target"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                true, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, -1));

        jLabel3.setText("Export to file:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTextField1.setText("d:/temp/result.tmx");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 190, -1));

        jButton1.setText("Browse");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jButton2.setText("Cancel");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jButton3.setText("Finish");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jButton4.setText("Next");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jButton5.setText("Previous");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
