/**
 * GAlignFrm.java
 *
 * Created on May 6, 2004, 12:45 AM
 */

package galign.ui.view;

import galign.Setup;

import java.util.LinkedList;
import java.util.ListIterator;

/**
 *
 * @author  cvdlaan
 */
public class GAlignFrm extends javax.swing.JFrame
{

    /** Creates new form GAlignFrm */
    public GAlignFrm ()
    {
        initComponents ();
        setSize(new java.awt.Dimension(800, 650));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        toolbar = new javax.swing.JToolBar();
        openProjectBtn = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        splitPane.setDividerLocation(150);
        treePane = new javax.swing.JScrollPane();
        projectTree = new javax.swing.JTree();
        splitPane2 = new javax.swing.JSplitPane();
        splitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane2.setDividerLocation(140);
        infoPane = new javax.swing.JScrollPane();
        contentPane = new javax.swing.JScrollPane();
        contentPane.getVerticalScrollBar().setUnitIncrement(18);

        splitPane2.setTopComponent(infoPane);
        splitPane2.setBottomComponent(contentPane);

        bottomPane = new javax.swing.JPanel();
        statusPane = new javax.swing.JPanel();
        legendPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_status = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        fileMnu = new javax.swing.JMenu();
        openProjectMni = new javax.swing.JMenuItem();
        closeProjectMni = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        uploadMni = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        exitMni = new javax.swing.JMenuItem();
        alignMnu = new javax.swing.JMenu();
        openAlignmentMni = new javax.swing.JMenuItem();
        saveAlignmentMni = new javax.swing.JMenuItem();
        closeAlignmentMni = new javax.swing.JMenuItem();
        removeAlignmentMni = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        optionsMni = new javax.swing.JMenuItem();
        //exportAsTmxMni = new javax.swing.JMenuItem();
        approveAllMni = new javax.swing.JMenuItem();
        helpMnu = new javax.swing.JMenu();
        helpMni = new javax.swing.JMenuItem();
        aboutMni = new javax.swing.JMenuItem();

        //getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().setLayout(new java.awt.BorderLayout());

        setTitle(Setup.getString("label.galign"));

        toolbar.setFloatable(false);
        openProjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/open.gif")));
        toolbar.add(openProjectBtn);


        //getContentPane().add(toolbar, java.awt.BorderLayout.NORTH);

        projectTree.setMinimumSize(new java.awt.Dimension(74, 64));
        projectTree.setModel(projectTree.getModel());
        treePane.setViewportView(projectTree);

        splitPane.setLeftComponent(treePane);
        splitPane.setRightComponent(splitPane2);
        splitPane.setDividerLocation(150);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        
        bottomPane.setLayout(new java.awt.GridLayout());
        bottomPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        statusPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(Setup.getLabel("label.status"));
        statusPane.add(jLabel1);
        lb_status.setText("");
        statusPane.add(lb_status);
        bottomPane.add(statusPane);

        legendPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        legendPane.setBackground(java.awt.Color.white);
        javax.swing.JLabel approved = new javax.swing.JLabel(
                    Setup.getLabel("label.approved") + ": ______________");
        approved.setForeground(java.awt.Color.green.darker());
        legendPane.add(approved);
        javax.swing.JLabel notapproved = new javax.swing.JLabel(
                "    " + Setup.getLabel("label.notapproved") + ": ______________");
        notapproved.setForeground(java.awt.Color.gray);
        legendPane.add(notapproved);
        bottomPane.add(legendPane);

        //getContentPane().add(statusPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 692, 20));
        getContentPane().add(bottomPane, java.awt.BorderLayout.SOUTH);

        fileMnu.setMnemonic(java.awt.event.KeyEvent.VK_F);
        fileMnu.setText(Setup.getString("menu.file"));
        openProjectMni.setMnemonic(java.awt.event.KeyEvent.VK_O);
        openProjectMni.setText(Setup.getString("menu.openProject"));
        fileMnu.add(openProjectMni);

        closeProjectMni.setText(Setup.getString("menu.closeProject"));
        closeProjectMni.setMnemonic(java.awt.event.KeyEvent.VK_C);
        closeProjectMni.setEnabled(false);
        fileMnu.add(closeProjectMni);

        fileMnu.add(jSeparator1);

        uploadMni.setMnemonic(java.awt.event.KeyEvent.VK_U);
        uploadMni.setText(Setup.getString("menu.upload")+"...");
        uploadMni.setEnabled(false);
        fileMnu.add(uploadMni);

        fileMnu.add(jSeparator2);

        exitMni.setMnemonic(java.awt.event.KeyEvent.VK_X);
        exitMni.setText(Setup.getString("menu.exit"));
        fileMnu.add(exitMni);

        menu.add(fileMnu);

        alignMnu.setMnemonic(java.awt.event.KeyEvent.VK_A);
        alignMnu.setText(Setup.getString("menu.align"));
        openAlignmentMni.setMnemonic(java.awt.event.KeyEvent.VK_O);
        openAlignmentMni.setText(Setup.getString("menu.openPage"));
        openAlignmentMni.setEnabled(false);
        alignMnu.add(openAlignmentMni);

        saveAlignmentMni.setMnemonic(java.awt.event.KeyEvent.VK_S);
        saveAlignmentMni.setText(Setup.getString("menu.savePage"));
        saveAlignmentMni.setEnabled(false);
        alignMnu.add(saveAlignmentMni);

        closeAlignmentMni.setMnemonic(java.awt.event.KeyEvent.VK_C);
        closeAlignmentMni.setText(Setup.getString("menu.closePage"));
        closeAlignmentMni.setEnabled(false);
        alignMnu.add(closeAlignmentMni);

        removeAlignmentMni.setMnemonic(java.awt.event.KeyEvent.VK_R);
        removeAlignmentMni.setText(Setup.getString("menu.removePage"));
        removeAlignmentMni.setEnabled(false);
        alignMnu.add(removeAlignmentMni);

        alignMnu.add(jSeparator5);
        approveAllMni.setMnemonic(java.awt.event.KeyEvent.VK_E);
        approveAllMni.setText(Setup.getString("menu.approveAll"));
        approveAllMni.setEnabled(false);
        alignMnu.add(approveAllMni);
/*
        exportAsTmxMni.setMnemonic(java.awt.event.KeyEvent.VK_E);
        exportAsTmxMni.setText(Setup.getString("menu.exportAsTmx"));
        exportAsTmxMni.setEnabled(false);
        alignMnu.add(exportAsTmxMni);

        alignMnu.add(jSeparator3);

        optionsMni.setMnemonic('O');
        optionsMni.setText("Options");
        alignMnu.add(optionsMni);
*/

        menu.add(alignMnu);

        helpMnu.setMnemonic(java.awt.event.KeyEvent.VK_H);
        helpMnu.setText(Setup.getString("menu.help"));
        helpMni.setMnemonic(java.awt.event.KeyEvent.VK_H);
        helpMni.setText(Setup.getString("menu.help"));
        helpMnu.add(helpMni);

        aboutMni.setMnemonic(java.awt.event.KeyEvent.VK_A);
        aboutMni.setText(Setup.getString("menu.aboutGalign"));
        helpMnu.add(aboutMni);

        menu.add(helpMnu);

        setJMenuBar(menu);

        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm (java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
    {
        System.exit (0);
    }//GEN-LAST:event_exitForm

    private javax.swing.tree.TreeModel getTree()
    {
        javax.swing.tree.DefaultMutableTreeNode root = new javax.swing.tree.DefaultMutableTreeNode("Demo Project");
        javax.swing.tree.DefaultTreeModel result = new javax.swing.tree.DefaultTreeModel(root);

        javax.swing.tree.DefaultMutableTreeNode dir1 = new javax.swing.tree.DefaultMutableTreeNode("dir en_US");
        javax.swing.tree.DefaultMutableTreeNode dir2 = new javax.swing.tree.DefaultMutableTreeNode("dir de_DE");

        javax.swing.tree.DefaultMutableTreeNode file1 = new javax.swing.tree.DefaultMutableTreeNode("abstract_en_US.html");
        javax.swing.tree.DefaultMutableTreeNode file2 = new javax.swing.tree.DefaultMutableTreeNode("abstract_de_DE.html");
        javax.swing.tree.DefaultMutableTreeNode file3 = new javax.swing.tree.DefaultMutableTreeNode("main_tm_export.tmx");

        root.add(dir1); dir1.add(file1); dir1.add(file2);
        root.add(dir2); dir2.add(file3);

        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        new GAlignFrm ().show ();
    }

     // Variables declaration - do not modify
    public javax.swing.JMenuItem aboutMni;
    public javax.swing.JMenu alignMnu;
    public javax.swing.JMenuItem closeAlignmentMni;
    public javax.swing.JMenuItem closeProjectMni;
    public javax.swing.JScrollPane contentPane;
    public javax.swing.JMenuItem exitMni;
    public javax.swing.JMenuItem approveAllMni;
    //public javax.swing.JMenuItem exportAsTmxMni;
    public javax.swing.JMenu fileMnu;
    public javax.swing.JMenuItem helpMni;
    public javax.swing.JMenu helpMnu;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JSeparator jSeparator5;
    public javax.swing.JLabel lb_status;
    public javax.swing.JMenuBar menu;
    public javax.swing.JMenuItem openAlignmentMni;
    public javax.swing.JMenuItem saveAlignmentMni;
    public javax.swing.JButton openProjectBtn;
    public javax.swing.JMenuItem openProjectMni;
    public javax.swing.JMenuItem optionsMni;
    public javax.swing.JTree projectTree;
    public javax.swing.JMenuItem removeAlignmentMni;
    public javax.swing.JSplitPane splitPane;
    public javax.swing.JPanel bottomPane;
    public javax.swing.JPanel statusPane;
    public javax.swing.JPanel legendPane;
    public javax.swing.JToolBar toolbar;
    public javax.swing.JScrollPane treePane;
    public javax.swing.JMenuItem uploadMni;
    public javax.swing.JScrollPane infoPane;
    public javax.swing.JSplitPane splitPane2;
    // End of variables declaration
}
