/*
 * NoProjectPnl.java
 *
 * Created on July 29, 2004, 12:28 AM
 */

package galign.ui.view;

import galign.Setup;

/**
 *
 * @author  cvdlaan
 */
public class NoProjectPnl extends javax.swing.JPanel
{
    
    /** Creates new form NoProjectPnl */
    public NoProjectPnl ()
    {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText(Setup.getString("msg.noproject"));
        add(jLabel1);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
