/*
 * ProjectAttributesPnl.java
 *
 * Created on May 10, 2004, 11:37 PM
 */

package galign.ui.view;

/**
 *
 * @author  cvdlaan
 */
public class ProjectAttributesPnl extends javax.swing.JPanel
{
    
    /** Creates new form ProjectAttributesPnl */
    public ProjectAttributesPnl ()
    {
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jLabel1 = new javax.swing.JLabel();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User-defined project properties:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Project", "Test"},
                {"Creator", "cvdlaan"},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Name", "Value"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        add(jTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 70));

        jButton1.setText("Add");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jButton2.setText("Remove");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jButton4.setText("Cancel");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jButton5.setText("Finish");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jButton6.setText("Next");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jButton7.setText("Back");
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

    }//GEN-END:initComponents

    private void jButton3ActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
